// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var accessKeysDeleteObjectStorageKeyCmd = &cobra.Command{
	Use:   "delete-object-storage-key",
	Long:  "Revokes an Object Storage access key. Once revoked, the access key can no longer be used by third-party clients. A successful request triggers an `obj_access_key_delete` [event](https://techdocs.akamai.com/linode-api/reference/get-events). > blue-book > > This operation has specific [rate limits](https://techdocs.akamai.com/linode-api/reference/rate-limits#specific-operation-rate-limits). **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `object_storage:read_write` **CLI** ```shell linode-cli object-storage keys-delete 12345 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Revoke an Object Storage access key",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/object-storage/keys/{keyId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		keyIdVal, _ := cmd.Flags().GetString("key-id")
		if keyIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "key-id")
		}
		path = strings.Replace(path, "{keyId}", keyIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	accessKeysDeleteObjectStorageKeyCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = accessKeysDeleteObjectStorageKeyCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = accessKeysDeleteObjectStorageKeyCmd.MarkFlagRequired("api-version")
	accessKeysDeleteObjectStorageKeyCmd.Flags().String("key-id", "", "The key to look up.")
	_ = accessKeysDeleteObjectStorageKeyCmd.MarkFlagRequired("key-id")
}
