// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var accountLoginsCmd = &cobra.Command{
	Use:   "account-logins",
	Long:  "Use these operations to review successful login data.",
	Short: "account-logins operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("account-logins", "Account logins")
}
