// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var accountCmd = &cobra.Command{
	Use:   "account",
	Long:  "Use account operations to review and update details about your Akamai Connected Cloud account, including billing information, promotions, and your specific information.",
	Short: "account operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("account", "Account")
}
