// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var accountAvailabilityCmd = &cobra.Command{
	Use:   "account-availability",
	Long:  "Use these operations to review the services available for use with your account.",
	Short: "account-availability operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("account-availability", "Account availability")
}
