// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var alertsDeleteNotificationChannelCmd = &cobra.Command{
	Use:   "delete-notification-channel",
	Long:  "__Limited availability__ Delete a specific monitoring alert notification channel with a `type` of `user`. You can't delete a `system` notification channel. You also can't delete a `user` channel that's actively used in an alert: 1. Run the [List alerts for a notification channel](https://techdocs.akamai.com/linode-api/reference/get-alerts-for-an-alert-channel) operation, using the stored `channelId` for your notification channel. 2. Store the `id` for each alert that uses the notification channel. 3. Run the [Update an alert definition](https://techdocs.akamai.com/linode-api/reference/put-alert-definition) operation for each stored alert `id`. Include the `channel_ids` object in the request and ensure that the notification `channelId` is _left out_. This removes the notification channel from the alert definition. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `monitor:read_write` **CLI** ```shell linode-cli alerts channels-delete 754 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Delete a notification channel",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/monitor/alert-channels/{channelId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		channelIdVal, _ := cmd.Flags().GetString("channel-id")
		if channelIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "channel-id")
		}
		path = strings.Replace(path, "{channelId}", channelIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	alertsDeleteNotificationChannelCmd.Flags().String("api-version", "", "__Enum__ Call the `v4beta` URL for operations still only in beta.")
	_ = alertsDeleteNotificationChannelCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = alertsDeleteNotificationChannelCmd.MarkFlagRequired("api-version")
	alertsDeleteNotificationChannelCmd.Flags().String("channel-id", "", "The unique identifier assigned to the monitoring alerts notification channel. Run the [List notification channels](https://techdocs.akamai.com/linode-api/reference/get-notification-channels) operation and store the `id` for the applicable one.")
	_ = alertsDeleteNotificationChannelCmd.MarkFlagRequired("channel-id")
}
