// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var attachmentsCmd = &cobra.Command{
	Use:   "attachments",
	Long:  "Mange any attachments you may need to include with your support tickets, such as log entry files and screenshot images.",
	Short: "attachments operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("attachments", "Attachments")
}
