// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var childAccountsGetCmd = &cobra.Command{
	Use:   "get",
	Long:  "__Deprecated__ Returns a paginated list of child accounts you're part of the account delegations for. > construction Parent and child accounts feature in Identity and Access > > With the introduction of Identity and Access, the parent and child accounts feature has changed. This operation is now deprecated, so use the [List child accounts](https://techdocs.akamai.com/linode-api/reference/get-iam-delegation-all-child-accounts) operation instead. To learn more about the changes, see [Changes to the parent and child accounts feature for migrated partners](https://techdocs.akamai.com/cloud-computing/docs/parent-child-migration-partner). **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `child_account:read_only` **CLI** ```shell linode-cli child-account list ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "List child accounts (Deprecated)",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/child-accounts"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	childAccountsGetCmd.Flags().String("page", "1", "The page of a collection to return.")
	childAccountsGetCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	childAccountsGetCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = childAccountsGetCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = childAccountsGetCmd.MarkFlagRequired("api-version")
}
