// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var controlPlaneAclCmd = &cobra.Command{
	Use:   "control-plane-acl",
	Long:  "View and manage access control lists (ACLs) for the control planes on your LKE clusters. Control Plane ACLs allow you to restrict access to your cluster's control plane to specific IP addresses or ranges.",
	Short: "control-plane-acl operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("control-plane-acl", "Control Plane ACL")
}
