// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var delegationForParentAndChildAccountsGetDelegationProfileChildAccountCmd = &cobra.Command{
	Use:   "get-delegation-profile-child-account",
	Long:  "Returns details on a specific child account you are part of the account delegation team for. To learn more about the parent and child accounts feature and account delegations, see [Parent and child accounts](https://techdocs.akamai.com/cloud-computing/docs/parent-and-child-accounts-for-akamai-partners). > blue-book Parent and child accounts feature > > This operation is available only within the context of the parent and child accounts feature and can be run only on a parent account. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `list_all_child_accounts`",
	Short: "Get a child account",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/iam/delegation/profile/child-accounts/{euuid}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		euuidVal, _ := cmd.Flags().GetString("euuid")
		if euuidVal == "" {
			return fmt.Errorf("required flag --%s not set", "euuid")
		}
		path = strings.Replace(path, "{euuid}", euuidVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	delegationForParentAndChildAccountsGetDelegationProfileChildAccountCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = delegationForParentAndChildAccountsGetDelegationProfileChildAccountCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = delegationForParentAndChildAccountsGetDelegationProfileChildAccountCmd.MarkFlagRequired("api-version")
	delegationForParentAndChildAccountsGetDelegationProfileChildAccountCmd.Flags().String("euuid", "", "A unique identifier for a child account. To get this value, run [List child accounts](https://techdocs.akamai.com/linode-api/reference/get-iam-delegation-all-child-accounts).")
	_ = delegationForParentAndChildAccountsGetDelegationProfileChildAccountCmd.MarkFlagRequired("euuid")
}
