// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var devicesCmd = &cobra.Command{
	Use:   "devices",
	Long:  "",
	Short: "devices operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("devices", "")
}
