// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var eventsCmd = &cobra.Command{
	Use:   "events",
	Long:  "An event represents an action you've taken on your account, over the last 90 days. Use these operations to review your current events.",
	Short: "events operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("events", "Events")
}
