// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var firewallSettingsCmd = &cobra.Command{
	Use:   "firewall-settings",
	Long:  "",
	Short: "firewall-settings operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("firewall-settings", "")
}
