// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var firewallsPutFirewallRulesCmd = &cobra.Command{
	Use:   "put-firewall-rules",
	Long:  "Updates the inbound and outbound Rules for a Firewall. - Assigned Linodes must not have any ongoing live migrations. - __Note__. This operation replaces all of a Firewall's `inbound` and `outbound` rulesets with the values specified in your request. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `update_firewall_rules` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `firewall:read_write` **CLI** ```shell linode-cli firewalls rules-update 123 \\ --inbound '[{\"action\":\"ACCEPT\", \"protocol\": \"TCP\", \"ports\": \"22, 80, 8080, 443\", \"addresses\": {\"ipv4\": [\"192.0.2.0/24\", \"198.51.100.2/32\"], \"ipv6\": [\"2001:DB8::/128\"]}}]' \\ --outbound '[{\"action\":\"DROP\",\"protocol\": \"TCP\", \"ports\": \"49152-65535\", \"addresses\": {\"ipv4\": [\"192.0.2.0/24\", \"198.51.100.2/32\"], \"ipv6\": [\"2001:DB8::/128`\"]}}]' ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Update firewall rules",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/networking/firewalls/{firewallId}/rules"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		firewallIdVal, _ := cmd.Flags().GetString("firewall-id")
		if firewallIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "firewall-id")
		}
		path = strings.Replace(path, "{firewallId}", firewallIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "inbound", JSONPath: "inbound", Type: "string"},
			{FlagName: "outbound", JSONPath: "outbound", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	firewallsPutFirewallRulesCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = firewallsPutFirewallRulesCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = firewallsPutFirewallRulesCmd.MarkFlagRequired("api-version")
	firewallsPutFirewallRulesCmd.Flags().String("firewall-id", "", "ID of the Firewall to access.")
	_ = firewallsPutFirewallRulesCmd.MarkFlagRequired("firewall-id")
	firewallsPutFirewallRulesCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	firewallsPutFirewallRulesCmd.Flags().String("inbound", "", "")
	firewallsPutFirewallRulesCmd.Flags().String("outbound", "", "")
}
