// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var generalCmd = &cobra.Command{
	Use:   "general",
	Long:  "Managed Databases is Akamai's fully-managed, high-performance database service. Use these operations to review general information for all of your databases.",
	Short: "general operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("general", "General")
}
