// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var generalGetDatabasesTypeCmd = &cobra.Command{
	Use:   "get-databases-type",
	Long:  "Display the details of a single Managed Databases node type. The type and number of nodes determine the resources and price of a Managed Databases instance. Run the [List Managed Databases type](https://techdocs.akamai.com/linode-api/reference/get-databases-types) operation and store the `id` for the applicable database node type. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Roles: `database_viewer` **CLI** ```shell linode-cli databases type-view ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get a Managed Databases type",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/types/{typeId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		typeIdVal, _ := cmd.Flags().GetString("type-id")
		if typeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "type-id")
		}
		path = strings.Replace(path, "{typeId}", typeIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	generalGetDatabasesTypeCmd.Flags().String("page", "1", "The page of a collection to return.")
	generalGetDatabasesTypeCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	generalGetDatabasesTypeCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = generalGetDatabasesTypeCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = generalGetDatabasesTypeCmd.MarkFlagRequired("api-version")
	generalGetDatabasesTypeCmd.Flags().String("type-id", "", "The ID of the Managed Database type.")
	_ = generalGetDatabasesTypeCmd.MarkFlagRequired("type-id")
}
