// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var grantsCmd = &cobra.Command{
	Use:   "grants",
	Long:  "View the grants (permissions) available to your user account.",
	Short: "grants operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("grants", "Grants")
}
