// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var identityManagementGetEntitiesCmd = &cobra.Command{
	Use:   "get-entities",
	Long:  "Lists entities created on the account. An *entity* is an object that has a life-cycle and can be managed by an authorized user within an account, for example: a specific virtual machine or firewall. You can manage an entity over time by performing operations on it, based on your access level. > blue-book Before you begin > > Before you run this operation, read [Comparison of Linode API for grants and Identity and Access](https://techdocs.akamai.com/cloud-computing/docs/migration-grants-identity-and-access#comparison-of-linode-api-for-grants-and-identity-and-access) to learn about the new experience and recommended use of the Identity and Access endpoints. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `list_entities`",
	Short: "List entities",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/entities"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	identityManagementGetEntitiesCmd.Flags().String("api-version", "", "__Enum__ Call the `v4` URL.")
	_ = identityManagementGetEntitiesCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = identityManagementGetEntitiesCmd.MarkFlagRequired("api-version")
}
