// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var imageSharingPutSharegroupTokenCmd = &cobra.Command{
	Use:   "put-sharegroup-token",
	Long:  "Updates the `label` of an existing membership token for a share group member or a pending membership. To get the `token_uuid`, run the [List tokens](https://techdocs.akamai.com/linode-api/reference/get-user-tokens) or [Create a token](https://techdocs.akamai.com/linode-api/reference/post-sharegroup-tokens) operation to generate one for the share group you want to join. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `images:read_write` **CLI** ```shell linode-cli image-sharegroups token-update abc123 --label \"new_label\" ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Update a token",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/images/sharegroups/tokens/{tokenUuid}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tokenUuidVal, _ := cmd.Flags().GetString("token-uuid")
		if tokenUuidVal == "" {
			return fmt.Errorf("required flag --%s not set", "token-uuid")
		}
		path = strings.Replace(path, "{tokenUuid}", tokenUuidVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "label", JSONPath: "label", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	imageSharingPutSharegroupTokenCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = imageSharingPutSharegroupTokenCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = imageSharingPutSharegroupTokenCmd.MarkFlagRequired("api-version")
	imageSharingPutSharegroupTokenCmd.Flags().String("token-uuid", "", "A unique identifier for the token, used to reference it after creation.")
	_ = imageSharingPutSharegroupTokenCmd.MarkFlagRequired("token-uuid")
	imageSharingPutSharegroupTokenCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	imageSharingPutSharegroupTokenCmd.Flags().String("label", "", "The descriptive name of the token.")
	_ = imageSharingPutSharegroupTokenCmd.MarkFlagRequired("label")
}
