// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var imageSharingDeleteSharegroupTokenCmd = &cobra.Command{
	Use:   "delete-sharegroup-token",
	Long:  "Removes an existing membership token for a share group member or a pending membership. - To get the `token_uuid`, run the [List tokens](https://techdocs.akamai.com/linode-api/reference/get-user-tokens) operation. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `images:read_write` **CLI** ```shell linode-cli image-sharegroups token-delete abc123 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Delete a token",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/images/sharegroups/tokens/{tokenUuid}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tokenUuidVal, _ := cmd.Flags().GetString("token-uuid")
		if tokenUuidVal == "" {
			return fmt.Errorf("required flag --%s not set", "token-uuid")
		}
		path = strings.Replace(path, "{tokenUuid}", tokenUuidVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	imageSharingDeleteSharegroupTokenCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = imageSharingDeleteSharegroupTokenCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = imageSharingDeleteSharegroupTokenCmd.MarkFlagRequired("api-version")
	imageSharingDeleteSharegroupTokenCmd.Flags().String("token-uuid", "", "A unique identifier for the token, used to reference it after creation.")
	_ = imageSharingDeleteSharegroupTokenCmd.MarkFlagRequired("token-uuid")
}
