// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var imageSharingGetSharegroupByTokenCmd = &cobra.Command{
	Use:   "get-sharegroup-by-token",
	Long:  "Gets details about a share group you're a member of. To get the `token_uuid`, run the [Get a token](https://techdocs.akamai.com/linode-api/reference/get-sharegroup-token) or [Create a token](https://techdocs.akamai.com/linode-api/reference/post-sharegroup-tokens) for the share group you want to join and share it with the group owner. You have to be accepted as a share group member before running this operation. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `images:read_only` **CLI** ```shell linode-cli image-sharegroups view-by-token abc123 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get a token's share group",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/images/sharegroups/tokens/{tokenUuid}/sharegroup"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tokenUuidVal, _ := cmd.Flags().GetString("token-uuid")
		if tokenUuidVal == "" {
			return fmt.Errorf("required flag --%s not set", "token-uuid")
		}
		path = strings.Replace(path, "{tokenUuid}", tokenUuidVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	imageSharingGetSharegroupByTokenCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = imageSharingGetSharegroupByTokenCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = imageSharingGetSharegroupByTokenCmd.MarkFlagRequired("api-version")
	imageSharingGetSharegroupByTokenCmd.Flags().String("token-uuid", "", "A unique identifier for the token, used to reference it after creation.")
	_ = imageSharingGetSharegroupByTokenCmd.MarkFlagRequired("token-uuid")
}
