// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var ipv4AddressesCmd = &cobra.Command{
	Use:   "ipv4-addresses",
	Long:  "",
	Short: "ipv4-addresses operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("ipv4-addresses", "")
}
