// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var ipv4AddressesPostShareIpv4sCmd = &cobra.Command{
	Use:   "post-share-ipv4s",
	Long:  "This operation is equivalent to [Share IP addresses](https://techdocs.akamai.com/linode-api/reference/post-share-ips). Configure shared IPs. IP sharing allows IP address reassignment (also referred to as IP failover) from one Linode to another if the primary Linode becomes unresponsive. This means that requests to the primary Linode's IP address can be automatically rerouted to secondary Linodes at the configured shared IP addresses. IP failover requires configuration of a [BGP based failover service](https://techdocs.akamai.com/cloud-computing/docs/configure-failover-on-a-compute-instance) within the internal system of the primary Linode. > blue-book > > A public IPv4 address can't be shared if it's configured for a 1:1 NAT on a legacy configuration profile VPC interface or on a Linode VPC interface. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `ips:read_write, linodes:read_write`",
	Short: "Configure IPv4 sharing",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/networking/ipv4/share"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "ips", JSONPath: "ips", Type: "array"},
			{FlagName: "linode-id", JSONPath: "linode_id", Type: "integer"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	ipv4AddressesPostShareIpv4sCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = ipv4AddressesPostShareIpv4sCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = ipv4AddressesPostShareIpv4sCmd.MarkFlagRequired("api-version")
	ipv4AddressesPostShareIpv4sCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	ipv4AddressesPostShareIpv4sCmd.Flags().String("ips", "", "A list of secondary Linode IPs to share with the primary Linode. - Can include both IPv4 addresses and IPv6 ranges (omit /56 and /64 prefix lengths) - Can include both private and public IPv4 addresses. - You must have access to all of these addresses and they must be in the same Region as the primary Linode. - Enter an empty array to remove all shared IP addresses.")
	_ = ipv4AddressesPostShareIpv4sCmd.MarkFlagRequired("ips")
	ipv4AddressesPostShareIpv4sCmd.Flags().String("linode-id", "", "The ID of the primary Linode that the addresses will be shared with.")
	_ = ipv4AddressesPostShareIpv4sCmd.MarkFlagRequired("linode-id")
}
