// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var ipv6RangesCmd = &cobra.Command{
	Use:   "ipv6-ranges",
	Long:  "",
	Short: "ipv6-ranges operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("ipv6-ranges", "")
}
