// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var ipv6RangesPostIpv6RangeCmd = &cobra.Command{
	Use:   "post-ipv6-range",
	Long:  "Creates an IPv6 Range and assigns it based on the provided Linode or route target IPv6 SLAAC address. See the `ipv6` property when running the [Get a Linode](https://techdocs.akamai.com/linode-api/reference/get-linode-instance) operation to view a Linode's IPv6 SLAAC address. - Either `linode_id` or `route_target` is required in a request. - `linode_id` and `route_target` are mutually exclusive. Submitting values for both properties in a request results in an error. - Upon a successful request, an IPv6 range is created in the [region](https://techdocs.akamai.com/linode-api/reference/get-regions) that corresponds to the provided `linode_id` or `route_target`. - Your Linode is responsible for routing individual addresses in the range, or handling traffic for all the addresses in the range. - Run the [Assign IP addresses](https://techdocs.akamai.com/linode-api/reference/post-assign-ips) operation to re-assign IPv6 Ranges to your Linodes. > blue-book > > - A Linode can only have one IPv6 range targeting its SLAAC address. > - An account can only have one IPv6 range in each [region](https://techdocs.akamai.com/linode-api/reference/get-regions). > - [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) to request expansion of these restrictions. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `ips:read_write, linodes:read_write` **CLI** ```shell linode-cli networking v6-range-create \\ --linode_id 123 \\ --prefix_length 64 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Create an IPv6 range",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/networking/ipv6/ranges"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "linode-id", JSONPath: "linode_id", Type: "integer"},
			{FlagName: "prefix-length", JSONPath: "prefix_length", Type: "integer"},
			{FlagName: "route-target", JSONPath: "route_target", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	ipv6RangesPostIpv6RangeCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = ipv6RangesPostIpv6RangeCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = ipv6RangesPostIpv6RangeCmd.MarkFlagRequired("api-version")
	ipv6RangesPostIpv6RangeCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	ipv6RangesPostIpv6RangeCmd.Flags().String("linode-id", "", "The ID of the Linode to assign this range to. The SLAAC address for the provided Linode is used as the range's `route_target`. - __Required__ if `route_target` is omitted from the request. - Mutually exclusive with `route_target`. Submitting values for both properties in a request results in an error.")
	ipv6RangesPostIpv6RangeCmd.Flags().String("prefix-length", "", "The prefix length of the IPv6 range.")
	_ = ipv6RangesPostIpv6RangeCmd.RegisterFlagCompletionFunc("prefix-length", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"56", "64"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = ipv6RangesPostIpv6RangeCmd.MarkFlagRequired("prefix-length")
	ipv6RangesPostIpv6RangeCmd.Flags().String("route-target", "", "The IPv6 SLAAC address to assign this range to. - __Required__ if `linode_id` is omitted from the request. - Mutually exclusive with `linode_id`. Submitting values for both properties in a request results in an error. > blue-book > > You need to omit the `/128` prefix length of the SLAAC address when using this property.")
}
