// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var kubeconfigsCmd = &cobra.Command{
	Use:   "kubeconfigs",
	Long:  "View or regenerate the kubeconfig files for your LKE clusters, which authenticate and configure access to your Kubernetes clusters.",
	Short: "kubeconfigs operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("kubeconfigs", "Kubeconfigs")
}
