// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var linodeInterfacesCmd = &cobra.Command{
	Use:   "linode-interfaces",
	Long:  "A Linode interface lets you set up networking on your Linode. A Linode interface links to the Linode, rather than to a legacy configuration profile. Use these operations to manage the Linode interfaces on your Linodes.",
	Short: "linode-interfaces operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("linode-interfaces", "Linode interfaces")
}
