// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var linodeInterfacesPutLinodeInterfaceSettingsCmd = &cobra.Command{
	Use:   "put-linode-interface-settings",
	Long:  "Updates Network Helper and default route settings on the Linode. Before enabling or disabling Network Helper, you need to power off the Linode. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `update_linode` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `linodes:read_write` **CLI** *Public interface* ```shell linode-cli linodes interface-settings-update $linodeId \\ --network_helper true \\ --default_route.ipv4_interface_id 4527 \\ --default_route.ipv6_interface_id 4541 \\ --default_route.ipv4_eligible_interface_ids 4527 \\ --default_route.ipv4_eligible_interface_ids 4541 \\ --default_route.ipv6_eligible_interface_ids 4527 \\ --default_route.ipv6_eligible_interface_ids 4541 ``` *VLAN interface* ```shell linode-cli linodes interface-settings-update $linodeId \\ --network_helper true ``` *VPC interface* ```shell linode-cli linodes interface-settings-update $linodeId \\ --network_helper true \\ --default_route.ipv4_interface_id 5527 \\ --default_route.ipv4_eligible_interface_ids 5527 \\ --default_route.ipv4_eligible_interface_ids 5541 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Update Linode interface settings",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/interfaces/settings"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "default-route.ipv4-eligible-interface-ids", JSONPath: "default_route.ipv4_eligible_interface_ids", Type: "array"},
			{FlagName: "default-route.ipv4-interface-id", JSONPath: "default_route.ipv4_interface_id", Type: "integer"},
			{FlagName: "default-route.ipv6-eligible-interface-ids", JSONPath: "default_route.ipv6_eligible_interface_ids", Type: "array"},
			{FlagName: "default-route.ipv6-interface-id", JSONPath: "default_route.ipv6_interface_id", Type: "integer"},
			{FlagName: "network-helper", JSONPath: "network_helper", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeInterfacesPutLinodeInterfaceSettingsCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeInterfacesPutLinodeInterfaceSettingsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeInterfacesPutLinodeInterfaceSettingsCmd.MarkFlagRequired("api-version")
	linodeInterfacesPutLinodeInterfaceSettingsCmd.Flags().String("linode-id", "", "The `id` of the Linode.")
	_ = linodeInterfacesPutLinodeInterfaceSettingsCmd.MarkFlagRequired("linode-id")
	linodeInterfacesPutLinodeInterfaceSettingsCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	linodeInterfacesPutLinodeInterfaceSettingsCmd.Flags().String("default-route.ipv4-eligible-interface-ids", "", "__Read-only__ The VPC or public interface IDs that are eligible to be the IPv4 `default_route` for this Linode. If the `ipv4_eligible_interface_ids` array is empty, this means there are no eligible interfaces eligible for the IPv4 default route role.")
	linodeInterfacesPutLinodeInterfaceSettingsCmd.Flags().String("default-route.ipv4-interface-id", "null", "The VPC or public interface ID assigned as the IPv4 `default_route`. The [List Linode interface settings](https://techdocs.akamai.com/linode-api/reference/get-linode-interface-settings) operation provides eligible IPv4 interface IDs.")
	linodeInterfacesPutLinodeInterfaceSettingsCmd.Flags().String("default-route.ipv6-eligible-interface-ids", "", "__Read-only__ The public interface IDs that are eligible to be the IPv6 `default_route` for this Linode. If the `ipv6_eligible_interface_ids` array is empty, this means there are no eligible interfaces eligible for the IPv6 default route role.")
	linodeInterfacesPutLinodeInterfaceSettingsCmd.Flags().String("default-route.ipv6-interface-id", "null", "The public interface ID assigned as the IPv6 `default_route`. The [List Linode interface settings](https://techdocs.akamai.com/linode-api/reference/get-linode-interface-settings) operation provides eligible IPv6 interface IDs.")
	linodeInterfacesPutLinodeInterfaceSettingsCmd.Flags().String("network-helper", "", "Enables the Network Helper feature. The default value is determined by the `network_helper` setting in the [account settings](https://techdocs.akamai.com/linode-api/reference/get-account-settings). [Power off the Linode](https://techdocs.akamai.com/linode-api/reference/post-shutdown-linode-instance) before disabling or enabling Network Helper.")
}
