// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var linodeInstancesPostRescueLinodeInstanceCmd = &cobra.Command{
	Use:   "post-rescue-linode-instance",
	Long:  "Rescue Mode is a safe environment for performing many system recovery and disk management tasks. Rescue Mode is based on the Finnix recovery distribution, a self-contained and bootable Linux distribution. You can also use Rescue Mode for tasks other than disaster recovery, such as formatting disks to use different filesystems, copying data between disks, and downloading files from a disk via SSH and SFTP. Linodes with legacy configuration interfaces receive a public IP and boot into the recovery Linux distribution. Linodes with Linode interfaces still boot into recovery mode with the recovery Linux distribution, but they retain their original network interfaces and settings from before entering rescue mode. - Note that `sdh` is reserved and unavailable during rescue. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `rescue_linode` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `linodes:read_write` **CLI** ```shell linode-cli linodes rescue 123 \\ --devices.sda.disk_id 124458 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Boot a Linode into rescue mode",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/rescue"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "devices.sda", JSONPath: "devices.sda", Type: "object"},
			{FlagName: "devices.sdb", JSONPath: "devices.sdb", Type: "object"},
			{FlagName: "devices.sdc", JSONPath: "devices.sdc", Type: "object"},
			{FlagName: "devices.sdd", JSONPath: "devices.sdd", Type: "object"},
			{FlagName: "devices.sde", JSONPath: "devices.sde", Type: "object"},
			{FlagName: "devices.sdf", JSONPath: "devices.sdf", Type: "object"},
			{FlagName: "devices.sdg", JSONPath: "devices.sdg", Type: "object"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeInstancesPostRescueLinodeInstanceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeInstancesPostRescueLinodeInstanceCmd.MarkFlagRequired("api-version")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("linode-id", "", "ID of the Linode to rescue.")
	_ = linodeInstancesPostRescueLinodeInstanceCmd.MarkFlagRequired("linode-id")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("devices.sda", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("devices.sdb", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("devices.sdc", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("devices.sdd", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("devices.sde", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("devices.sdf", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	linodeInstancesPostRescueLinodeInstanceCmd.Flags().String("devices.sdg", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
}
