// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var linodeFirewallsCmd = &cobra.Command{
	Use:   "linode-firewalls",
	Long:  "Use these operations to manage the firewalls applied to your Linodes.",
	Short: "linode-firewalls operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("linode-firewalls", "Linode firewalls")
}
