// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var linodeIpAddressesPutLinodeIpCmd = &cobra.Command{
	Use:   "put-linode-ip",
	Long:  "Updates the reverse DNS (RDNS) for a Linode's IP Address. This may be done for both IPv4 and IPv6 addresses. Setting the RDNS to `null` for a public IPv4 address, resets it to the default `ip.linodeusercontent.com` RDNS value. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `update_linode` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `linodes:read_write` **CLI** ```shell linode-cli linodes ip-update 123 \\ 203.0.113.1 \\ --rdns test.example.org ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Update an IP address's RDNS for a Linode",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/ips/{address}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)
		addressVal, _ := cmd.Flags().GetString("address")
		if addressVal == "" {
			return fmt.Errorf("required flag --%s not set", "address")
		}
		path = strings.Replace(path, "{address}", addressVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "rdns", JSONPath: "rdns", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeIpAddressesPutLinodeIpCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeIpAddressesPutLinodeIpCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeIpAddressesPutLinodeIpCmd.MarkFlagRequired("api-version")
	linodeIpAddressesPutLinodeIpCmd.Flags().String("linode-id", "", "The ID of the Linode.")
	_ = linodeIpAddressesPutLinodeIpCmd.MarkFlagRequired("linode-id")
	linodeIpAddressesPutLinodeIpCmd.Flags().String("address", "", "The IP address.")
	_ = linodeIpAddressesPutLinodeIpCmd.MarkFlagRequired("address")
	linodeIpAddressesPutLinodeIpCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	linodeIpAddressesPutLinodeIpCmd.Flags().String("rdns", "", "The reverse DNS assigned to this address. For public IPv4 addresses, this will be set to a default value provided by Linode if not explicitly set.")
	_ = linodeIpAddressesPutLinodeIpCmd.MarkFlagRequired("rdns")
}
