// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var linodeDisksPostCloneLinodeDiskCmd = &cobra.Command{
	Use:   "post-clone-linode-disk",
	Long:  "Copies a disk, byte-for-byte, into a new disk on the same Linode. The operation fails if the target doesn't have enough storage space. A Linode can have up to 50 disks. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `clone_linode_disk` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `linodes:read_write` **CLI** ```shell linode-cli linodes disk-clone ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Clone a disk",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/disks/{diskId}/clone"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)
		diskIdVal, _ := cmd.Flags().GetString("disk-id")
		if diskIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "disk-id")
		}
		path = strings.Replace(path, "{diskId}", diskIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("POST", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeDisksPostCloneLinodeDiskCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeDisksPostCloneLinodeDiskCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeDisksPostCloneLinodeDiskCmd.MarkFlagRequired("api-version")
	linodeDisksPostCloneLinodeDiskCmd.Flags().String("linode-id", "", "ID of the Linode to look up.")
	_ = linodeDisksPostCloneLinodeDiskCmd.MarkFlagRequired("linode-id")
	linodeDisksPostCloneLinodeDiskCmd.Flags().String("disk-id", "", "ID of the Disk to clone.")
	_ = linodeDisksPostCloneLinodeDiskCmd.MarkFlagRequired("disk-id")
}
