// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var linodeStatisticsGetLinodeTransferCmd = &cobra.Command{
	Use:   "get-linode-transfer",
	Long:  "Returns a Linode's network transfer pool statistics for the current month. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `view_linode_monthly_network_transfer_stats` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `linodes:read_only` **CLI** ```shell linode-cli linodes transfer-view 123 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get this month's network transfer stats",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/transfer"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeStatisticsGetLinodeTransferCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeStatisticsGetLinodeTransferCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeStatisticsGetLinodeTransferCmd.MarkFlagRequired("api-version")
	linodeStatisticsGetLinodeTransferCmd.Flags().String("linode-id", "", "ID of the Linode to look up.")
	_ = linodeStatisticsGetLinodeTransferCmd.MarkFlagRequired("linode-id")
}
