// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var linodeStatisticsGetNodeBalancerStatsCmd = &cobra.Command{
	Use:   "get-node-balancer-stats",
	Long:  "Returns detailed statistics about the requested NodeBalancer. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `view_nodebalancer_statistics` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `nodebalancers:read_only`",
	Short: "Get NodeBalancer statistics",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/nodebalancers/{nodeBalancerId}/stats"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		nodeBalancerIdVal, _ := cmd.Flags().GetString("node-balancer-id")
		if nodeBalancerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "node-balancer-id")
		}
		path = strings.Replace(path, "{nodeBalancerId}", nodeBalancerIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeStatisticsGetNodeBalancerStatsCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeStatisticsGetNodeBalancerStatsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeStatisticsGetNodeBalancerStatsCmd.MarkFlagRequired("api-version")
	linodeStatisticsGetNodeBalancerStatsCmd.Flags().String("node-balancer-id", "", "The ID of the NodeBalancer.")
	_ = linodeStatisticsGetNodeBalancerStatsCmd.MarkFlagRequired("node-balancer-id")
}
