// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var linodeNodebalancersCmd = &cobra.Command{
	Use:   "linode-nodebalancers",
	Long:  "A NodeBalancer is a managed load balancer that intelligently distributes incoming requests to multiple backend Linodes, so that there's no single point of failure. Use these operations to review the NodeBalancers assigned to your Linodes.",
	Short: "linode-nodebalancers operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("linode-nodebalancers", "Linode NodeBalancers")
}
