// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var linodeInterfacesGetLinodeInterfaceFirewallsCmd = &cobra.Command{
	Use:   "get-linode-interface-firewalls",
	Long:  "Lists firewalls assigned to an interface. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `view_linode` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `nodebalancers:read_only` **CLI** ```shell linode-cli linodes interface-firewalls-list $linodeId $interfaceId ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "List Linode interface firewalls",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/interfaces/{interfaceId}/firewalls"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)
		interfaceIdVal, _ := cmd.Flags().GetString("interface-id")
		if interfaceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "interface-id")
		}
		path = strings.Replace(path, "{interfaceId}", interfaceIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeInterfacesGetLinodeInterfaceFirewallsCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeInterfacesGetLinodeInterfaceFirewallsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeInterfacesGetLinodeInterfaceFirewallsCmd.MarkFlagRequired("api-version")
	linodeInterfacesGetLinodeInterfaceFirewallsCmd.Flags().String("linode-id", "", "The `id` of the Linode.")
	_ = linodeInterfacesGetLinodeInterfaceFirewallsCmd.MarkFlagRequired("linode-id")
	linodeInterfacesGetLinodeInterfaceFirewallsCmd.Flags().String("interface-id", "", "The `id` of the Linode interface.")
	_ = linodeInterfacesGetLinodeInterfaceFirewallsCmd.MarkFlagRequired("interface-id")
}
