// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var lkeNodesDeleteLkeClusterNodeCmd = &cobra.Command{
	Use:   "delete-lke-cluster-node",
	Long:  "Deletes a specific node from a node pool. __Deleting a Node is a destructive action and cannot be undone.__ Deleting a node reduces the size of the node pool it belongs to. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Roles: `lkecluster_admin` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `lke:read_write` **CLI** ```shell linode-cli lke node-delete 12345 12345-6aa78910bc ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Delete a node",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/lke/clusters/{clusterId}/nodes/{nodeId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		clusterIdVal, _ := cmd.Flags().GetString("cluster-id")
		if clusterIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "cluster-id")
		}
		path = strings.Replace(path, "{clusterId}", clusterIdVal, 1)
		nodeIdVal, _ := cmd.Flags().GetString("node-id")
		if nodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "node-id")
		}
		path = strings.Replace(path, "{nodeId}", nodeIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	lkeNodesDeleteLkeClusterNodeCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = lkeNodesDeleteLkeClusterNodeCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = lkeNodesDeleteLkeClusterNodeCmd.MarkFlagRequired("api-version")
	lkeNodesDeleteLkeClusterNodeCmd.Flags().String("cluster-id", "", "ID of the Kubernetes cluster containing the Node.")
	_ = lkeNodesDeleteLkeClusterNodeCmd.MarkFlagRequired("cluster-id")
	lkeNodesDeleteLkeClusterNodeCmd.Flags().String("node-id", "", "The ID of the Node to access.")
	_ = lkeNodesDeleteLkeClusterNodeCmd.MarkFlagRequired("node-id")
}
