// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var lkeClustersGetLkeClusterCmd = &cobra.Command{
	Use:   "get-lke-cluster",
	Long:  "Get a specific Cluster by ID. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Roles: `lkecluster_viewer` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `lke:read_only` **CLI** ```shell linode-cli lke cluster-view 12345 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get a Kubernetes cluster",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/lke/clusters/{clusterId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		clusterIdVal, _ := cmd.Flags().GetString("cluster-id")
		if clusterIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "cluster-id")
		}
		path = strings.Replace(path, "{clusterId}", clusterIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	lkeClustersGetLkeClusterCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = lkeClustersGetLkeClusterCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = lkeClustersGetLkeClusterCmd.MarkFlagRequired("api-version")
	lkeClustersGetLkeClusterCmd.Flags().String("cluster-id", "", "ID of the Kubernetes cluster to look up.")
	_ = lkeClustersGetLkeClusterCmd.MarkFlagRequired("cluster-id")
}
