// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var logsGetDestinationsCmd = &cobra.Command{
	Use:   "get-destinations",
	Long:  "Returns all available logs destinations. Destinations are used as sync points for log data. This operation can only be accessed by account [users](https://techdocs.akamai.com/linode-api/reference/get-users) with _unrestricted_ access. Talk to your local account administrator about access management. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `monitor:read_only` **CLI** ```shell linode-cli streams destinations-list ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "List destinations",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/monitor/streams/destinations"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	logsGetDestinationsCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = logsGetDestinationsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = logsGetDestinationsCmd.MarkFlagRequired("api-version")
}
