// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var logsPutDestinationCmd = &cobra.Command{
	Use:   "put-destination",
	Long:  "Update an existing logs destination. Include the appropriate `destinationId` as a path parameter. This operation can only be accessed by account [users](https://techdocs.akamai.com/linode-api/reference/get-users) with _unrestricted_ access. Talk to your local account administrator about access management. > construction > > By using this service, you acknowledge your obligations under the United States Department of Justice Bulk Sensitive Data Transaction Rule (\"BSD Rule\"). You also agree that you will not use the service to transfer, onward transfer, or otherwise make accessible any United States government-related data or bulk United States sensitive personal data to countries of concern or a covered person, as each of those terms and concepts are defined in the [BSD Rule](https://www.federalregister.gov/documents/2024/03/01/2024-04573/preventing-access-to-americans-bulk-sensitive-personal-data-and-united-states-government-related). Anyone using the service is solely responsible for compliance with the BSD Rule. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `monitor:read_write` **CLI** ```shell linode-cli streams destination-update 456 \\ --label New destination for Managed Database logs \\ --details.host secondary-bucket-1.us-east-12.linodeobjects.com \\ --details.bucket_name secondary-bucket \\ --details.region us-east \\ --details.path audit-logs \\ --details.access_key_id 456 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Update a destination",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/monitor/streams/destinations/{destinationId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		destinationIdVal, _ := cmd.Flags().GetString("destination-id")
		if destinationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "destination-id")
		}
		path = strings.Replace(path, "{destinationId}", destinationIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "created", JSONPath: "created", Type: "string"},
			{FlagName: "created-by", JSONPath: "created_by", Type: "string"},
			{FlagName: "details", JSONPath: "details", Type: "string"},
			{FlagName: "id", JSONPath: "id", Type: "integer"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "type", JSONPath: "type", Type: "string"},
			{FlagName: "updated", JSONPath: "updated", Type: "string"},
			{FlagName: "updated-by", JSONPath: "updated_by", Type: "string"},
			{FlagName: "version", JSONPath: "version", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	logsPutDestinationCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = logsPutDestinationCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = logsPutDestinationCmd.MarkFlagRequired("api-version")
	logsPutDestinationCmd.Flags().String("destination-id", "", "The unique identifier assigned to the logs destination. Run the [List destinations](https://techdocs.akamai.com/linode-api/reference/get-destinations) operation and store the `id` for the applicable one.")
	_ = logsPutDestinationCmd.MarkFlagRequired("destination-id")
	logsPutDestinationCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	logsPutDestinationCmd.Flags().String("created", "", "__Read-only__ When the logs destination was created.")
	logsPutDestinationCmd.Flags().String("created-by", "", "__Read-only__ The name of the user on your account that created the logs destination.")
	logsPutDestinationCmd.Flags().String("details", "", "")
	logsPutDestinationCmd.Flags().String("id", "", "__Read-only__ The unique identifier assigned to the stream.")
	logsPutDestinationCmd.Flags().String("label", "", "The name of the destination object. Used for display purposes.")
	logsPutDestinationCmd.Flags().String("type", "", "The type of destination for log data sync, either `akamai_object_storage` if Object Storage is the destination, or `custom_https` for a unique URL.")
	_ = logsPutDestinationCmd.RegisterFlagCompletionFunc("type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"akamai_object_storage", "custom_https"}, cobra.ShellCompDirectiveNoFileComp
	})
	logsPutDestinationCmd.Flags().String("updated", "", "__Read-only__ When the logs destination was last updated. This is the same as `created` if the destination hasn't been updated.")
	logsPutDestinationCmd.Flags().String("updated-by", "", "__Read-only__ The name of the user on your account that last updated the logs destination. If it hasn't been updated, this value is the same as `created_by`.")
	logsPutDestinationCmd.Flags().String("version", "", "__Read-only__ The version of the destination.")
}
