// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var maintenancePoliciesGetCmd = &cobra.Command{
	Use:   "get",
	Long:  "List all available maintenance policies that can be applied to your Linodes. **CLI** ```shell linode-cli maintenance policies-list ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "List maintenance policies",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/maintenance/policies"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	maintenancePoliciesGetCmd.Flags().String("api-version", "", "__Enum__ Call the `v4beta` URL for operations still only in beta.")
	_ = maintenancePoliciesGetCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = maintenancePoliciesGetCmd.MarkFlagRequired("api-version")
}
