// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var managedServiceMonitorsPostManagedServiceCmd = &cobra.Command{
	Use:   "post-managed-service",
	Long:  "Creates a service monitor. Linode Managed monitors this service and alerts Akamai Support when issues are detected. This operation can only be accessed by the unrestricted users of an account. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_write` **CLI** ```shell linode-cli managed service-create \\ --service_type url \\ --label prod-1 \\ --address \"https://example.org\" \\ --timeout 30 \\ --body \"it worked\" \\ --consultation_group on-call \\ --notes \"The service name is \\ my-cool-application\" \\ --credentials 9991 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Create a managed service",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/managed/services"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	managedServiceMonitorsPostManagedServiceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = managedServiceMonitorsPostManagedServiceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = managedServiceMonitorsPostManagedServiceCmd.MarkFlagRequired("api-version")
	managedServiceMonitorsPostManagedServiceCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
}
