// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var metricsPostGetTokenCmd = &cobra.Command{
	Use:   "post-get-token",
	Long:  "__Limited availability__ Returns a token that authenticates requests for the entities within a specific service type. To see your currently supported services, run the [List supported service types](https://techdocs.akamai.com/linode-api/reference/get-monitor-services) operation. The token has a lifetime of six hours after you create it. > blue-book > > When creating this token for Object Storage metrics, the token is accessible to all users on your account. > thumbs-up There's a tutorial > > We offer an [example](https://techdocs.akamai.com/linode-api/reference/get-started#authenticate-monitor-api-operations) you can follow to generate this token. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `monitor:read_only` **CLI** ```shell linode-cli monitor token-get dbaas \\ --entity_ids 189690 \\ --entity_ids 188020 --json ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Create a token for a service type",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/monitor/services/{serviceType}/token"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		serviceTypeVal, _ := cmd.Flags().GetString("service-type")
		if serviceTypeVal == "" {
			return fmt.Errorf("required flag --%s not set", "service-type")
		}
		path = strings.Replace(path, "{serviceType}", serviceTypeVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	metricsPostGetTokenCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = metricsPostGetTokenCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = metricsPostGetTokenCmd.MarkFlagRequired("api-version")
	metricsPostGetTokenCmd.Flags().String("service-type", "", "The Akamai Cloud Computing service being monitored. To see your currently supported services, run the [List supported service types](https://techdocs.akamai.com/linode-api/reference/get-monitor-services) operation and store the appropriate `service_type`.")
	_ = metricsPostGetTokenCmd.MarkFlagRequired("service-type")
	metricsPostGetTokenCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
}
