// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var mysqlSuspendDatabasesMysqlInstanceCmd = &cobra.Command{
	Use:   "suspend-databases-mysql-instance",
	Long:  "Suspend a MySQL Managed Database from your account, releasing idle resources and keeping only necessary data. All service data is lost if there are no backups available. This halts billing for the cluster. - The database's status needs to be `active`. - Akamai deletes suspended clusters after 180 days. - A successful request triggers a `database_update` [event](https://techdocs.akamai.com/linode-api/reference/get-events). **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Roles: `database_admin` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `databases:read_write` **CLI** ```shell linode-cli databases mysql-suspend 123 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Suspend a MySQL Managed Database",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/mysql/instances/{mysqlInstanceId}/suspend"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		mysqlInstanceIdVal, _ := cmd.Flags().GetString("mysql-instance-id")
		if mysqlInstanceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "mysql-instance-id")
		}
		path = strings.Replace(path, "{mysqlInstanceId}", mysqlInstanceIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("POST", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	mysqlSuspendDatabasesMysqlInstanceCmd.Flags().String("api-version", "", "__Enum__ Call the `v4` URL.")
	_ = mysqlSuspendDatabasesMysqlInstanceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = mysqlSuspendDatabasesMysqlInstanceCmd.MarkFlagRequired("api-version")
	mysqlSuspendDatabasesMysqlInstanceCmd.Flags().String("mysql-instance-id", "", "The unique identifier for a MySQL Managed Database. Run the [List MySQL Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-mysql-instances) operation and store the `id` for the desired one.")
	_ = mysqlSuspendDatabasesMysqlInstanceCmd.MarkFlagRequired("mysql-instance-id")
}
