// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var nodebalancerTypesCmd = &cobra.Command{
	Use:   "nodebalancer-types",
	Long:  "",
	Short: "nodebalancer-types operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("nodebalancer-types", "")
}
