// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var nodebalancersDeleteNodeBalancerCmd = &cobra.Command{
	Use:   "delete-node-balancer",
	Long:  "Deletes a NodeBalancer. __This is a destructive action and cannot be undone.__ A NodeBalancer can't be deleted if it has a `cannot_delete` or a `cannot_delete_with_subresources` lock. Only account administrators can remove locks using the [Delete a resource lock](https://techdocs.akamai.com/linode-api/reference/delete-resource-lock) operation. Deleting a NodeBalancer also deletes all associated configurations and nodes. However, the backend servers represented by these nodes are not changed or removed. When you delete a NodeBalancer, you lose access to the IP addresses assigned to it. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `delete_nodebalancer` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `nodebalancers:read_write` **CLI** ```shell linode-cli nodebalancers delete 12345 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Delete a NodeBalancer",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/nodebalancers/{nodeBalancerId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		nodeBalancerIdVal, _ := cmd.Flags().GetString("node-balancer-id")
		if nodeBalancerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "node-balancer-id")
		}
		path = strings.Replace(path, "{nodeBalancerId}", nodeBalancerIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	nodebalancersDeleteNodeBalancerCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = nodebalancersDeleteNodeBalancerCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = nodebalancersDeleteNodeBalancerCmd.MarkFlagRequired("api-version")
	nodebalancersDeleteNodeBalancerCmd.Flags().String("node-balancer-id", "", "The ID of the NodeBalancer.")
	_ = nodebalancersDeleteNodeBalancerCmd.MarkFlagRequired("node-balancer-id")
}
