// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var nodesCmd = &cobra.Command{
	Use:   "nodes",
	Long:  "",
	Short: "nodes operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("nodes", "")
}
