// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var nodesGetNodeBalancerConfigCmd = &cobra.Command{
	Use:   "get-node-balancer-config",
	Long:  "Returns a paginated list of NodeBalancer nodes associated with this Config. These are the backends that will be sent traffic for this port. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `list_nodebalancer_config_nodes` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `nodebalancers:read_only` **CLI** ```shell linode-cli nodebalancers nodes-list 12345 4567 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "List nodes",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/nodebalancers/{nodeBalancerId}/configs/{configId}/nodes"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		nodeBalancerIdVal, _ := cmd.Flags().GetString("node-balancer-id")
		if nodeBalancerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "node-balancer-id")
		}
		path = strings.Replace(path, "{nodeBalancerId}", nodeBalancerIdVal, 1)
		configIdVal, _ := cmd.Flags().GetString("config-id")
		if configIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "config-id")
		}
		path = strings.Replace(path, "{configId}", configIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	nodesGetNodeBalancerConfigCmd.Flags().String("page", "1", "The page of a collection to return.")
	nodesGetNodeBalancerConfigCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	nodesGetNodeBalancerConfigCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = nodesGetNodeBalancerConfigCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = nodesGetNodeBalancerConfigCmd.MarkFlagRequired("api-version")
	nodesGetNodeBalancerConfigCmd.Flags().String("node-balancer-id", "", "The ID of the NodeBalancer.")
	_ = nodesGetNodeBalancerConfigCmd.MarkFlagRequired("node-balancer-id")
	nodesGetNodeBalancerConfigCmd.Flags().String("config-id", "", "The ID of the NodeBalancer config to access.")
	_ = nodesGetNodeBalancerConfigCmd.MarkFlagRequired("config-id")
}
