// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var oauthAppsCmd = &cobra.Command{
	Use:   "oauth-apps",
	Long:  "View authorized apps that have been granted access to your account. You can also revoke access for any authorized app.",
	Short: "oauth-apps operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("oauth-apps", "OAuth apps")
}
