// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var personalAccessTokensPostPersonalAccessTokenCmd = &cobra.Command{
	Use:   "post-personal-access-token",
	Long:  "Creates a personal access token for your User. The raw token will be returned in the response, but will never be returned again afterward so be sure to take note of it. You may create a token with _at most_ the scopes of your current token. The created token will be able to access your account until the given expiry, or until it's revoked. __Parent and child accounts__ In the context of the [parent and child accounts](https://techdocs.akamai.com/cloud-computing/docs/parent-and-child-accounts-for-akamai-partners) feature, delegate users can't use personal access tokens on child accounts. You need to [create a delegate user token](https://techdocs.akamai.com/linode-api/reference/post-iam-delegation-profile-child-account-token) instead. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `create_profile_pat` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_write` **CLI** ```shell linode-cli profile token-create \\ --scopes '*' \\ --expiry '2018-01-01T13:46:32' \\ --label linode-cli ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Create a personal access token",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/profile/tokens"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "expiry", JSONPath: "expiry", Type: "string"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "scopes", JSONPath: "scopes", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	personalAccessTokensPostPersonalAccessTokenCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = personalAccessTokensPostPersonalAccessTokenCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = personalAccessTokensPostPersonalAccessTokenCmd.MarkFlagRequired("api-version")
	personalAccessTokensPostPersonalAccessTokenCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	personalAccessTokensPostPersonalAccessTokenCmd.Flags().String("expiry", "", "When this token should be valid until. If omitted, the new token will be valid until it is manually revoked.")
	personalAccessTokensPostPersonalAccessTokenCmd.Flags().String("label", "", "__Filterable__ This token's label. This is for display purposes only, but can be used to more easily track what you're using each token for.")
	personalAccessTokensPostPersonalAccessTokenCmd.Flags().String("scopes", "", "The access [scopes](https://techdocs.akamai.com/linode-api/reference/get-started#oauth-reference) to grant to the created token. These cannot be changed after creation, and may not exceed the scopes of the acting token. If omitted or entered with a wildcard character (`*`), the new token will have the same scopes as the acting token. Multiple scopes are separated by a space character (` `). For example, `linodes:read_write account:read_only`.")
}
