// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var postgresqlResumeDatabasesPostgreSqlInstanceCmd = &cobra.Command{
	Use:   "resume-databases-postgre-sql-instance",
	Long:  "Resume a suspended PostgreSQL Managed Database from your account. This resumes billing for the cluster. - The database's status needs to be `suspended`. - A successful request triggers a `database_resume` [event](https://techdocs.akamai.com/linode-api/reference/get-events). **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Roles: `database_admin` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `databases:read_write` **CLI** ```shell linode-cli databases postgresql-resume 123 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Resume a PostgreSQL Managed Database",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/postgresql/instances/{postgresqlInstanceId}/resume"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		postgresqlInstanceIdVal, _ := cmd.Flags().GetString("postgresql-instance-id")
		if postgresqlInstanceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "postgresql-instance-id")
		}
		path = strings.Replace(path, "{postgresqlInstanceId}", postgresqlInstanceIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("POST", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	postgresqlResumeDatabasesPostgreSqlInstanceCmd.Flags().String("api-version", "", "__Enum__ Call the `v4` URL.")
	_ = postgresqlResumeDatabasesPostgreSqlInstanceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = postgresqlResumeDatabasesPostgreSqlInstanceCmd.MarkFlagRequired("api-version")
	postgresqlResumeDatabasesPostgreSqlInstanceCmd.Flags().String("postgresql-instance-id", "", "The unique identifier for a PostgreSQL Managed Database. Run the [List PostgreSQL Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-postgre-sql-instances) operation and store the `id` for the desired one.")
	_ = postgresqlResumeDatabasesPostgreSqlInstanceCmd.MarkFlagRequired("postgresql-instance-id")
}
