// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var postgresqlCmd = &cobra.Command{
	Use:   "postgresql",
	Long:  "Managed Databases is Akamai's fully-managed, high-performance database service. Use these operations to create and manage clusters for PostgreSQL engine databases.",
	Short: "postgresql operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("postgresql", "PostgreSQL")
}
