// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var postgresqlGetDatabasesPostgreSqlConnPoolCmd = &cobra.Command{
	Use:   "get-databases-postgre-sql-conn-pool",
	Long:  "Returns a specific connection pool for a PostgreSQL Managed Database. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Roles: `database_viewer` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `databases:read_only` **CLI** ```shell linode-cli postgresql-conn-pool-view 890 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get a PostgreSQL connection pool",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/postgresql/instances/{postgresqlInstanceId}/connection-pools/{poolName}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		postgresqlInstanceIdVal, _ := cmd.Flags().GetString("postgresql-instance-id")
		if postgresqlInstanceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "postgresql-instance-id")
		}
		path = strings.Replace(path, "{postgresqlInstanceId}", postgresqlInstanceIdVal, 1)
		poolNameVal, _ := cmd.Flags().GetString("pool-name")
		if poolNameVal == "" {
			return fmt.Errorf("required flag --%s not set", "pool-name")
		}
		path = strings.Replace(path, "{poolName}", poolNameVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	postgresqlGetDatabasesPostgreSqlConnPoolCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = postgresqlGetDatabasesPostgreSqlConnPoolCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = postgresqlGetDatabasesPostgreSqlConnPoolCmd.MarkFlagRequired("api-version")
	postgresqlGetDatabasesPostgreSqlConnPoolCmd.Flags().String("postgresql-instance-id", "", "The unique identifier for a PostgreSQL Managed Database. Run the [List PostgreSQL Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-postgre-sql-instances) operation and store the `id` for the desired one.")
	_ = postgresqlGetDatabasesPostgreSqlConnPoolCmd.MarkFlagRequired("postgresql-instance-id")
	postgresqlGetDatabasesPostgreSqlConnPoolCmd.Flags().String("pool-name", "", "The `label` set for a specific connection pool in a PostgreSQL Managed Database. Run the [List PostgreSQL connection pools](https://techdocs.akamai.com/linode-api/reference/get-databases-postgre-sql-conn-pools) operation and store the `label` for the desired one.")
	_ = postgresqlGetDatabasesPostgreSqlConnPoolCmd.MarkFlagRequired("pool-name")
}
