// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var quotasGetObjectStorageGlobalQuotaUsageCmd = &cobra.Command{
	Use:   "get-object-storage-global-quota-usage",
	Long:  "Returns usage data for a specific global quota (`objGlobalQuotaId`). This includes the maximum number of resources permitted by the quota and your current usage for that resource. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `view_object_storage_usage` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `object_storage:read_only` **CLI** ```shell linode-cli object-storage global-quota-usage-view keys ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get Object Storage global quota usage data",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/object-storage/global-quotas/{objGlobalQuotaId}/usage"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		objGlobalQuotaIdVal, _ := cmd.Flags().GetString("obj-global-quota-id")
		if objGlobalQuotaIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "obj-global-quota-id")
		}
		path = strings.Replace(path, "{objGlobalQuotaId}", objGlobalQuotaIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	quotasGetObjectStorageGlobalQuotaUsageCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = quotasGetObjectStorageGlobalQuotaUsageCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = quotasGetObjectStorageGlobalQuotaUsageCmd.MarkFlagRequired("api-version")
	quotasGetObjectStorageGlobalQuotaUsageCmd.Flags().String("obj-global-quota-id", "", "__Enum__ Identifies the Object Storage-related global quota to retrieve.")
	_ = quotasGetObjectStorageGlobalQuotaUsageCmd.RegisterFlagCompletionFunc("obj-global-quota-id", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"keys"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = quotasGetObjectStorageGlobalQuotaUsageCmd.MarkFlagRequired("obj-global-quota-id")
}
