// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var regionsCmd = &cobra.Command{
	Use:   "regions",
	Long:  "Use these operations to view information about the various Akamai cloud computing data center regions, including their service capabilities, the country where they exist, their current status, and more.",
	Short: "regions operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("regions", "Regions")
}
