// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var resourceLocksDeleteResourceLockCmd = &cobra.Command{
	Use:   "delete-resource-lock",
	Long:  "__Beta__ Delete a specific resource lock. Once deleted, the resource it was assigned to is unlocked, and that resource can be deleted. This operation can only be accessed by account [users](https://techdocs.akamai.com/linode-api/reference/get-users) with _unrestricted_ access. Talk to your local account administrator about access management. > blue-book > > For specific delete instructions and requirements, see the relevant resource's delete operation documentation. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_write` **CLI** ```shell linode-cli resource-locks delete 25 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Delete a resource lock",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/locks/{resourceLockId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		resourceLockIdVal, _ := cmd.Flags().GetString("resource-lock-id")
		if resourceLockIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "resource-lock-id")
		}
		path = strings.Replace(path, "{resourceLockId}", resourceLockIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	resourceLocksDeleteResourceLockCmd.Flags().String("api-version", "", "__Enum__ Call the `v4beta` URL for operations still only in beta.")
	_ = resourceLocksDeleteResourceLockCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = resourceLocksDeleteResourceLockCmd.MarkFlagRequired("api-version")
	resourceLocksDeleteResourceLockCmd.Flags().String("resource-lock-id", "", "The unique identifier assigned to the resource lock. Run the [List resource locks](https://techdocs.akamai.com/linode-api/reference/get-locks) operation and store the `id` for the applicable resource lock.")
	_ = resourceLocksDeleteResourceLockCmd.MarkFlagRequired("resource-lock-id")
}
