// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var serviceTransfersDeleteServiceTransferCmd = &cobra.Command{
	Use:   "delete-service-transfer",
	Long:  "Cancels the service transfer for the provided `token`. These points apply to canceling a service transfer: - An cancellation notification is sent to the email address that's assigned to the account that requested the transfer. - Once canceled, the transfer can't be accepted or acted on in any way. If you cancel by mistake, you need to [create](https://techdocs.akamai.com/linode-api/reference/post-service-transfer) a new service transfer. - You can't cancel a service transfer if it's expired or it's been [accepted](https://techdocs.akamai.com/linode-api/reference/post-accept-service-transfer). **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `cancel_service_transfer` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_write` **CLI** ```shell linode-cli service-transfers \\ cancel 123E4567-E89B-12D3-A456-426614174000 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Cancel a service transfer",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/service-transfers/{token}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tokenVal, _ := cmd.Flags().GetString("token")
		if tokenVal == "" {
			return fmt.Errorf("required flag --%s not set", "token")
		}
		path = strings.Replace(path, "{token}", tokenVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	serviceTransfersDeleteServiceTransferCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = serviceTransfersDeleteServiceTransferCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = serviceTransfersDeleteServiceTransferCmd.MarkFlagRequired("api-version")
	serviceTransfersDeleteServiceTransferCmd.Flags().String("token", "", "The UUID of the service transfer. This value is sent in an email to the originator of the service transfer request.")
	_ = serviceTransfersDeleteServiceTransferCmd.MarkFlagRequired("token")
}
