// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var serviceTransfersGetServiceTransferCmd = &cobra.Command{
	Use:   "get-service-transfer",
	Long:  "Returns details for the service transfer for the provided `token`. - After a transfer has been [accepted](https://techdocs.akamai.com/linode-api/reference/post-accept-service-transfer), it can only be viewed by users on the accounts that [requested](https://techdocs.akamai.com/linode-api/reference/post-service-transfer) and [accepted](https://techdocs.akamai.com/linode-api/reference/post-accept-service-transfer) the transfer and have the corresponding permissions. - If [canceled](https://techdocs.akamai.com/linode-api/reference/delete-service-transfer) or expired, only users of the account that requested the transfer can view it and have the required permission. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `view_service_transfer` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_only` **CLI** ```shell linode-cli service-transfers \\ view 123E4567-E89B-12D3-A456-426614174000 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get a service transfer request",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/service-transfers/{token}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tokenVal, _ := cmd.Flags().GetString("token")
		if tokenVal == "" {
			return fmt.Errorf("required flag --%s not set", "token")
		}
		path = strings.Replace(path, "{token}", tokenVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	serviceTransfersGetServiceTransferCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = serviceTransfersGetServiceTransferCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = serviceTransfersGetServiceTransferCmd.MarkFlagRequired("api-version")
	serviceTransfersGetServiceTransferCmd.Flags().String("token", "", "The UUID of the service transfer. This value is sent in an email to the originator of the service transfer request.")
	_ = serviceTransfersGetServiceTransferCmd.MarkFlagRequired("token")
}
