// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var sshKeysCmd = &cobra.Command{
	Use:   "ssh-keys",
	Long:  "Manage SSH keys for your user account. When creating a Linode, you can choose to have one or more SSH keys automatically added to the new Linode for secure access.",
	Short: "ssh-keys operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("ssh-keys", "SSH keys")
}
