// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var sshKeysGetSshKeyCmd = &cobra.Command{
	Use:   "get-ssh-key",
	Long:  "Returns a single SSH Key object identified by `id` that you have access to view. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `view_profile_ssh_key` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_only` **CLI** ```shell linode-cli sshkeys view 42 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get an SSH key",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/profile/sshkeys/{sshKeyId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		sshKeyIdVal, _ := cmd.Flags().GetString("ssh-key-id")
		if sshKeyIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "ssh-key-id")
		}
		path = strings.Replace(path, "{sshKeyId}", sshKeyIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	sshKeysGetSshKeyCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = sshKeysGetSshKeyCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = sshKeysGetSshKeyCmd.MarkFlagRequired("api-version")
	sshKeysGetSshKeyCmd.Flags().String("ssh-key-id", "", "The ID of the SSHKey.")
	_ = sshKeysGetSshKeyCmd.MarkFlagRequired("ssh-key-id")
}
