// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var stackscriptsCmd = &cobra.Command{
	Use:   "stackscripts",
	Long:  "Create and manage StackScripts, reusable scripts that run during the deployment of new Linode instances to automate custom configurations.",
	Short: "stackscripts operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("stackscripts", "StackScripts")
}
