// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var supportTicketsGetTicketsCmd = &cobra.Command{
	Use:   "get-tickets",
	Long:  "Returns a collection of all support tickets opened from your account. This includes tickets you've opened and tickets generated by Linode customer support regarding your account. Open tickets are returned first in the response. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_only` **CLI** ```shell linode-cli tickets list ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "List support tickets",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/support/tickets"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	supportTicketsGetTicketsCmd.Flags().String("page", "1", "The page of a collection to return.")
	supportTicketsGetTicketsCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	supportTicketsGetTicketsCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = supportTicketsGetTicketsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = supportTicketsGetTicketsCmd.MarkFlagRequired("api-version")
}
