// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var supportTicketsPostCloseTicketCmd = &cobra.Command{
	Use:   "post-close-ticket",
	Long:  "Closes a support ticket you have access to modify. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_write` **CLI** ```shell linode-cli tickets close 11223344 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Close a support ticket",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/support/tickets/{ticketId}/close"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		ticketIdVal, _ := cmd.Flags().GetString("ticket-id")
		if ticketIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "ticket-id")
		}
		path = strings.Replace(path, "{ticketId}", ticketIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("POST", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	supportTicketsPostCloseTicketCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = supportTicketsPostCloseTicketCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = supportTicketsPostCloseTicketCmd.MarkFlagRequired("api-version")
	supportTicketsPostCloseTicketCmd.Flags().String("ticket-id", "", "The ID of the support ticket.")
	_ = supportTicketsPostCloseTicketCmd.MarkFlagRequired("ticket-id")
}
