// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var tagsDeleteTagCmd = &cobra.Command{
	Use:   "delete-tag",
	Long:  "Removes a tag from all objects and deletes it. This operation can only be accessed by account users with _unrestricted_ access. Talk to your local account administrator about access management. > blue-book > > Tags without any related objects are periodically cleaned up by the system. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_write` **CLI** ```shell linode-cli tags delete linode-cli tags rm ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Delete a tag",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/tags/{tagLabel}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tagLabelVal, _ := cmd.Flags().GetString("tag-label")
		if tagLabelVal == "" {
			return fmt.Errorf("required flag --%s not set", "tag-label")
		}
		path = strings.Replace(path, "{tagLabel}", tagLabelVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	tagsDeleteTagCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = tagsDeleteTagCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = tagsDeleteTagCmd.MarkFlagRequired("api-version")
	tagsDeleteTagCmd.Flags().String("tag-label", "", "The `label` of the tag to access.")
	_ = tagsDeleteTagCmd.MarkFlagRequired("tag-label")
}
