// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var tagsGetTaggedObjectsCmd = &cobra.Command{
	Use:   "get-tagged-objects",
	Long:  "Returns a paginated list of all objects you've tagged with the specified tag. The response includes a mixed collection of all object types. This operation can only be accessed by account users with _unrestricted_ access. Talk to your local account administrator about access management. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_only`",
	Short: "List tagged objects",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/tags/{tagLabel}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tagLabelVal, _ := cmd.Flags().GetString("tag-label")
		if tagLabelVal == "" {
			return fmt.Errorf("required flag --%s not set", "tag-label")
		}
		path = strings.Replace(path, "{tagLabel}", tagLabelVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	tagsGetTaggedObjectsCmd.Flags().String("page", "1", "The page of a collection to return.")
	tagsGetTaggedObjectsCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	tagsGetTaggedObjectsCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = tagsGetTaggedObjectsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = tagsGetTaggedObjectsCmd.MarkFlagRequired("api-version")
	tagsGetTaggedObjectsCmd.Flags().String("tag-label", "", "The `label` of the tag to access.")
	_ = tagsGetTaggedObjectsCmd.MarkFlagRequired("tag-label")
}
