// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var tagsPostTagCmd = &cobra.Command{
	Use:   "post-tag",
	Long:  "Creates a new tag and lets you optionally add it to specific objects. Tags are labels you can attach to objects in your account. Use them to specify and group attributes of objects that are relevant to you. Currently, you can add a tag to your `linodes`, your `nodebalancers`, the `domains` for your Linodes, and the `volumes` on your Linodes. > blue-book > > - This operation can only be accessed by account users with _unrestricted_ access. Talk to your local account administrator about access management. > > - If you don't add a tag to a supported object with this operation, you can use that object's update operation to later add the tag you created. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_write` **CLI** ```shell linode-cli tags create \\ --label 'example tag' \\ --linodes 123 \\ --linodes 456 \\ --volumes 9082 \\ --volumes 10003 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Create a tag",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/tags"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "domains", JSONPath: "domains", Type: "array"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "linodes", JSONPath: "linodes", Type: "array"},
			{FlagName: "nodebalancers", JSONPath: "nodebalancers", Type: "array"},
			{FlagName: "volumes", JSONPath: "volumes", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	tagsPostTagCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = tagsPostTagCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = tagsPostTagCmd.MarkFlagRequired("api-version")
	tagsPostTagCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	tagsPostTagCmd.Flags().String("domains", "", "The `id` values for the domains where you want to apply the tag. You need `read_write` access to each domain. If you don't, the API won't create the tag and you'll receive an error. You can run the [List domains](https://techdocs.akamai.com/linode-api/reference/get-domains) operation to store the `id` for desired domains and to review any `tags` currently applied.")
	tagsPostTagCmd.Flags().String("label", "", "The name of your tag. This is used for display purposes.")
	_ = tagsPostTagCmd.MarkFlagRequired("label")
	tagsPostTagCmd.Flags().String("linodes", "", "The `id` values for the Linodes where you want to apply the tag. You need `read_write` access to each Linode. If you don't, the API won't create the tag and you'll receive an error. You can run the [List Linodes](https://techdocs.akamai.com/linode-api/reference/get-linode-instances) operation to store the `id` for desired Linodes and to review any `tags` currently applied.")
	tagsPostTagCmd.Flags().String("nodebalancers", "", "The `id` values for the NodeBalancers where you want to apply the tag. You need `read_write` access to each NodeBalancer. If you don't, the API won't create the tag and you'll receive an error. You can run the [List NodeBalancers](https://techdocs.akamai.com/linode-api/reference/get-node-balancers) operation to store the `id` for desired NodeBalancers and to review any `tags` currently applied.")
	tagsPostTagCmd.Flags().String("volumes", "", "The `id` values for the Linode volumes where you want to apply the tag. You need `read_write` access to each volume. If you don't, the API won't create the tag and you'll receive an error. You can run the [List volumes](https://techdocs.akamai.com/linode-api/reference/get-volumes) operation to store the `id` for desired Linode volumes and to review any `tags` currently applied.")
}
