// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var templatesGetFirewallTemplateCmd = &cobra.Command{
	Use:   "get-firewall-template",
	Long:  "Gets a `vpc` or `public` firewall template you can use with Linode VPC and public interfaces. Firewall templates come with some protection rules already configured. The public interface's firewall template allows for login with SSH, and regular networking control data. You should further strengthen these rules by limiting the allowed IPv4 and IPv6 ranges. The VPC interface's firewall template allows for login with SSH, regular networking control data, and inbound traffic from the VPC address space. You should further strengthen these rules by limiting the allowed IPv4 and IPv6 ranges. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `Internet facing, no permission` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `firewall:read_only` **CLI** ```shell linode-cli firewalls template-view vpc ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Get a firewall template",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/networking/firewalls/templates/{slug}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		slugVal, _ := cmd.Flags().GetString("slug")
		if slugVal == "" {
			return fmt.Errorf("required flag --%s not set", "slug")
		}
		path = strings.Replace(path, "{slug}", slugVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	templatesGetFirewallTemplateCmd.Flags().String("page", "1", "The page of a collection to return.")
	templatesGetFirewallTemplateCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	templatesGetFirewallTemplateCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = templatesGetFirewallTemplateCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = templatesGetFirewallTemplateCmd.MarkFlagRequired("api-version")
	templatesGetFirewallTemplateCmd.Flags().String("slug", "", "__Enum__ The firewall template type, available for either `vpc` or `public` interfaces.")
	_ = templatesGetFirewallTemplateCmd.RegisterFlagCompletionFunc("slug", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"vpc", "public"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = templatesGetFirewallTemplateCmd.MarkFlagRequired("slug")
}
