// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var usersGetCmd = &cobra.Command{
	Use:   "get",
	Long:  "Returns a paginated list of all users on your account. A user can access all or part of an account based on their role assignment: - **Unrestricted access**. These users can access everything on an account. - **Restricted access**. These users can only access entities or perform actions they've been given specific grants to. > construction RBAC Identity and Access > > If Identity and Access is enabled on your account, the *restricted* users have the `account_admin` role and *restricted* users have [specific roles assigned to them](https://techdocs.akamai.com/linode-api/reference/get-iam-users-role-permissions). To learn more, see [Identity and Access for Akamai Cloud](https://techdocs.akamai.com/cloud-computing/docs/identity-and-access-cm). tabs: - syntax: | linode-cli users list title: CLI url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `view_user` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `account:read_only`",
	Short: "List users",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/users"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	usersGetCmd.Flags().String("page", "1", "The page of a collection to return.")
	usersGetCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	usersGetCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = usersGetCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = usersGetCmd.MarkFlagRequired("api-version")
}
