// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var vlansCmd = &cobra.Command{
	Use:   "vlans",
	Long:  "",
	Short: "vlans operations",
}

func init() {
	DisplayNames.RegisterCommandLongName("vlans", "")
}
