// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var volumesPostAttachVolumeCmd = &cobra.Command{
	Use:   "post-attach-volume",
	Long:  "Attach a Block Storage volume to an existing Linode. > blue-book > > - The volume and its target Linode need to exist in the same `region`. You can run the [List volumes](https://techdocs.akamai.com/linode-api/reference/get-volumes) and [List Linodes](https://techdocs.akamai.com/linode-api/reference/get-linode-instances) operations and review the `region` for each. > > - There's a maximum number of volumes that can be attached to a single Linode configuration. This number varies, based on the Linode's plan, with higher plan types supporting more volumes. The maximum follows a formula of the Linode plan's `total_ram / 1024`, with a minimum of 8 and a total maximum of 64 volumes. Rescue configurations support a maximum of 8. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `attach_volume` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `volumes:read_write, linodes:read_write` **CLI** ```shell linode-cli volumes attach 12345 \\ --linode_id 12346 \\ --config_id 23456 ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Attach a volume",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/volumes/{volumeId}/attach"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		volumeIdVal, _ := cmd.Flags().GetString("volume-id")
		if volumeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "volume-id")
		}
		path = strings.Replace(path, "{volumeId}", volumeIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "config-id", JSONPath: "config_id", Type: "integer"},
			{FlagName: "linode-id", JSONPath: "linode_id", Type: "integer"},
			{FlagName: "persist-across-boots", JSONPath: "persist_across_boots", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	volumesPostAttachVolumeCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = volumesPostAttachVolumeCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = volumesPostAttachVolumeCmd.MarkFlagRequired("api-version")
	volumesPostAttachVolumeCmd.Flags().String("volume-id", "", "The unique identifier for the target volume. Run the [List volumes](https://techdocs.akamai.com/linode-api/reference/get-volumes) operation and store the `id` for the target volume as your `volumeId`.")
	_ = volumesPostAttachVolumeCmd.MarkFlagRequired("volume-id")
	volumesPostAttachVolumeCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	volumesPostAttachVolumeCmd.Flags().String("config-id", "", "The unique identifier assigned to the Linode configuration where you want to include this volume. Run the [List configuration profiles](https://techdocs.akamai.com/linode-api/reference/get-linode-configs) operation and store the `id` for the target configuration. > blue-book > > - The configuration needs to belong to the Linode referenced by `linode_id`. > > - If you don't include this value, the API uses the last booted configuration.")
	volumesPostAttachVolumeCmd.Flags().String("linode-id", "", "The unique identifier assigned to the Linode where you want to attach the volume. Run the [List Linodes](https://techdocs.akamai.com/linode-api/reference/get-linode-instances) operation and store the `id` for the target Linode.")
	_ = volumesPostAttachVolumeCmd.MarkFlagRequired("linode-id")
	volumesPostAttachVolumeCmd.Flags().String("persist-across-boots", "true", "If set to `false`, the volume won't be attached to the Linode configuration. In this case, more than eight volumes may be attached to a Linode if a Linode has 16GB of RAM or more. The number of volumes you can attach is equal to the number of GB of RAM that the Linode has, up to a maximum of 64. If you set this to `false`, you can't include a `config_id` and only the `linode_id` should be passed. > blue-book > > To use this object, the target `linode_id` needs to have a status of `running`. Run the [List Linodes](https://techdocs.akamai.com/linode-api/reference/get-linode-instances) operation to check the `status` of each Linode.")
}
