// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/runtime"
	"github.com/spf13/cobra"
)

var vpcsDeleteVpcCmd = &cobra.Command{
	Use:   "delete-vpc",
	Long:  "Delete a single VPC and all of its Subnets. - A successful request triggers a `vpc_delete` event and `subnet_delete` events for each deleted VPC Subnet. - All of the VPC's subnets need to be eligible for deletion. You need to delete all network interfaces each subnet is assigned to. If those interfaces are active, you need to shut down the associated Linodes first. If any subnet can't be deleted, it prevents the VPC and its subnets from being deleted. - You can't delete a VPC if a NodeBalancer or a managed database is attached to one of its subnets. **Permissions and scopes** To call this operation, you need permissions, based on the model you're using: - **Identity and access permissions**. Your user needs a role with these permissions. [Learn more](https://techdocs.akamai.com/cloud-computing/docs/identity-access-cm-available-roles). - Permissions: `delete_vpc` - **OAuth scopes**. Your user needs these scopes assigned. [Learn more](https://techdocs.akamai.com/linode-api/reference/get-started#oauth). - Scopes: `vpc:read_write` **CLI** ```shell linode-cli vpcs delete $vpcId ``` [Learn more](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)",
	Short: "Delete a VPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/vpcs/{vpcId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		vpcIdVal, _ := cmd.Flags().GetString("vpc-id")
		if vpcIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "vpc-id")
		}
		path = strings.Replace(path, "{vpcId}", vpcIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	vpcsDeleteVpcCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = vpcsDeleteVpcCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = vpcsDeleteVpcCmd.MarkFlagRequired("api-version")
	vpcsDeleteVpcCmd.Flags().String("vpc-id", "", "The `id` of the VPC.")
	_ = vpcsDeleteVpcCmd.MarkFlagRequired("vpc-id")
}
