// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var accessKeysPutObjectStorageKeyCmd = &cobra.Command{
	Use:   "put-object-storage-key",
	Short: "Update an Object Storage access key",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/object-storage/keys/{keyId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		keyIdVal, _ := cmd.Flags().GetString("key-id")
		if keyIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "key-id")
		}
		path = strings.Replace(path, "{keyId}", keyIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "regions", JSONPath: "regions", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	accessKeysPutObjectStorageKeyCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = accessKeysPutObjectStorageKeyCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = accessKeysPutObjectStorageKeyCmd.MarkFlagRequired("api-version")
	accessKeysPutObjectStorageKeyCmd.Flags().String("key-id", "", "The key to look up.")
	_ = accessKeysPutObjectStorageKeyCmd.MarkFlagRequired("key-id")
	accessKeysPutObjectStorageKeyCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	accessKeysPutObjectStorageKeyCmd.Flags().String("label", "", "The label for the Object Storage key. Used for display purposes. Omit this to leave the `label` unchanged.")
	accessKeysPutObjectStorageKeyCmd.Flags().String("regions", "", "Replace the current list of `regions` set in a specific key. Include an existing region to keep it, or leave it out to remove it. Omit the `regions` array to leave the existing list unchanged. If you include new `regions` in the key, you can't immediately use the key to manage content in buckets in those regions. You need to grant these keys this access using [bucket policies](https://techdocs.akamai.com/cloud-computing/docs/define-access-and-permissions-using-bucket-policies). > construction Limited keys have restrictions > > These points apply to keys you've [created](https://techdocs.akamai.com/linode-api/reference/post-object-storage-keys) using the `bucket_access` array: > > - You can't remove a `region` from a limited key's original `bucket_access` list. If you include the `regions` array in this operation and target a limited key, you need to include all existing `region` entries from the `bucket_access` array. Otherwise, the operation fails with an error. Run [Get an Object Storage key](https://techdocs.akamai.com/linode-api/reference/get-object-storage-key) to review current `region` entries in a limited key. > > - If you need to remove a specific region from an active limited key, you can [revoke the key](https://techdocs.akamai.com/linode-api/reference/delete-object-storage-key) and create a new Object Storage key, without the specific region.")
}
