// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var accountLoginsGetAccountLoginCmd = &cobra.Command{
	Use:   "get-account-login",
	Short: "Get an account login",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/logins/{loginId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		loginIdVal, _ := cmd.Flags().GetString("login-id")
		if loginIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "login-id")
		}
		path = strings.Replace(path, "{loginId}", loginIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	accountLoginsGetAccountLoginCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = accountLoginsGetAccountLoginCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = accountLoginsGetAccountLoginCmd.MarkFlagRequired("api-version")
	accountLoginsGetAccountLoginCmd.Flags().String("login-id", "", "The ID of the login object to access.")
	_ = accountLoginsGetAccountLoginCmd.MarkFlagRequired("login-id")
}
