// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var accountTransferCmd = &cobra.Command{
	Use:   "account-transfer",
	Short: "account-transfer operations",
}
