// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var alertsGetAlertDefinitionsCmd = &cobra.Command{
	Use:   "get-alert-definitions",
	Short: "List alert definitions",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/monitor/alert-definitions"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	alertsGetAlertDefinitionsCmd.Flags().String("api-version", "", "__Enum__ Call the `v4beta` URL for operations still only in beta.")
	_ = alertsGetAlertDefinitionsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = alertsGetAlertDefinitionsCmd.MarkFlagRequired("api-version")
}
