// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var bucketsGetObjectStorageBucketCmd = &cobra.Command{
	Use:   "get-object-storage-bucket",
	Short: "Get an Object Storage bucket",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/object-storage/buckets/{regionId}/{bucket}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		regionIdVal, _ := cmd.Flags().GetString("region-id")
		if regionIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "region-id")
		}
		path = strings.Replace(path, "{regionId}", regionIdVal, 1)
		bucketVal, _ := cmd.Flags().GetString("bucket")
		if bucketVal == "" {
			return fmt.Errorf("required flag --%s not set", "bucket")
		}
		path = strings.Replace(path, "{bucket}", bucketVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	bucketsGetObjectStorageBucketCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = bucketsGetObjectStorageBucketCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = bucketsGetObjectStorageBucketCmd.MarkFlagRequired("api-version")
	bucketsGetObjectStorageBucketCmd.Flags().String("region-id", "", "Identifies a region where this bucket lives. > blue-book > > You can use a `clusterId` in place of `regionId` in requests for buckets that you created using the legacy version of the API. Run [List clusters](https://techdocs.akamai.com/linode-api/reference/get-object-storage-clusters) to see each cluster `id`.")
	_ = bucketsGetObjectStorageBucketCmd.MarkFlagRequired("region-id")
	bucketsGetObjectStorageBucketCmd.Flags().String("bucket", "", "The bucket name.")
	_ = bucketsGetObjectStorageBucketCmd.MarkFlagRequired("bucket")
}
