// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var bucketsPostObjectStorageBucketAccessCmd = &cobra.Command{
	Use:   "post-object-storage-bucket-access",
	Short: "Allow access to an Object Storage bucket",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/object-storage/buckets/{regionId}/{bucket}/access"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		regionIdVal, _ := cmd.Flags().GetString("region-id")
		if regionIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "region-id")
		}
		path = strings.Replace(path, "{regionId}", regionIdVal, 1)
		bucketVal, _ := cmd.Flags().GetString("bucket")
		if bucketVal == "" {
			return fmt.Errorf("required flag --%s not set", "bucket")
		}
		path = strings.Replace(path, "{bucket}", bucketVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "acl", JSONPath: "acl", Type: "string"},
			{FlagName: "cors-enabled", JSONPath: "cors_enabled", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	bucketsPostObjectStorageBucketAccessCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = bucketsPostObjectStorageBucketAccessCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = bucketsPostObjectStorageBucketAccessCmd.MarkFlagRequired("api-version")
	bucketsPostObjectStorageBucketAccessCmd.Flags().String("region-id", "", "Identifies a region where this bucket lives. > blue-book > > You can use a `clusterId` in place of `regionId` in requests for buckets that you created using the legacy version of the API. Run [List clusters](https://techdocs.akamai.com/linode-api/reference/get-object-storage-clusters) to see each cluster `id`.")
	_ = bucketsPostObjectStorageBucketAccessCmd.MarkFlagRequired("region-id")
	bucketsPostObjectStorageBucketAccessCmd.Flags().String("bucket", "", "The bucket name.")
	_ = bucketsPostObjectStorageBucketAccessCmd.MarkFlagRequired("bucket")
	bucketsPostObjectStorageBucketAccessCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	bucketsPostObjectStorageBucketAccessCmd.Flags().String("acl", "", "The S3 predefined collection of grantees and permissions set for the bucket, also referred to as a [Canned ACL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl).")
	_ = bucketsPostObjectStorageBucketAccessCmd.RegisterFlagCompletionFunc("acl", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"private", "public-read", "authenticated-read", "public-read-write", "custom"}, cobra.ShellCompDirectiveNoFileComp
	})
	bucketsPostObjectStorageBucketAccessCmd.Flags().String("cors-enabled", "", "If `true`, cross-origin resource sharing (CORS) is enabled for all origins in the bucket.")
}
