// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var configurationsCmd = &cobra.Command{
	Use:   "configurations",
	Short: "configurations operations",
}
