// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var configurationProfileInterfacesGetLinodeConfigInterfaceCmd = &cobra.Command{
	Use:   "get-linode-config-interface",
	Short: "Get a configuration profile interface",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/configs/{configId}/interfaces/{interfaceId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)
		configIdVal, _ := cmd.Flags().GetString("config-id")
		if configIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "config-id")
		}
		path = strings.Replace(path, "{configId}", configIdVal, 1)
		interfaceIdVal, _ := cmd.Flags().GetString("interface-id")
		if interfaceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "interface-id")
		}
		path = strings.Replace(path, "{interfaceId}", interfaceIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	configurationProfileInterfacesGetLinodeConfigInterfaceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = configurationProfileInterfacesGetLinodeConfigInterfaceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = configurationProfileInterfacesGetLinodeConfigInterfaceCmd.MarkFlagRequired("api-version")
	configurationProfileInterfacesGetLinodeConfigInterfaceCmd.Flags().String("linode-id", "", "The `id` of the Linode.")
	_ = configurationProfileInterfacesGetLinodeConfigInterfaceCmd.MarkFlagRequired("linode-id")
	configurationProfileInterfacesGetLinodeConfigInterfaceCmd.Flags().String("config-id", "", "The `id` of the Configuration Profile.")
	_ = configurationProfileInterfacesGetLinodeConfigInterfaceCmd.MarkFlagRequired("config-id")
	configurationProfileInterfacesGetLinodeConfigInterfaceCmd.Flags().String("interface-id", "", "The `id` of the Linode Configuration Profile Interface.")
	_ = configurationProfileInterfacesGetLinodeConfigInterfaceCmd.MarkFlagRequired("interface-id")
}
