// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var configurationProfilesPutLinodeConfigCmd = &cobra.Command{
	Use:   "put-linode-config",
	Short: "Update a configuration profile",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/configs/{configId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)
		configIdVal, _ := cmd.Flags().GetString("config-id")
		if configIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "config-id")
		}
		path = strings.Replace(path, "{configId}", configIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "comments", JSONPath: "comments", Type: "string"},
			{FlagName: "devices.sda", JSONPath: "devices.sda", Type: "object"},
			{FlagName: "devices.sdb", JSONPath: "devices.sdb", Type: "object"},
			{FlagName: "devices.sdc", JSONPath: "devices.sdc", Type: "object"},
			{FlagName: "devices.sdd", JSONPath: "devices.sdd", Type: "object"},
			{FlagName: "devices.sde", JSONPath: "devices.sde", Type: "object"},
			{FlagName: "devices.sdf", JSONPath: "devices.sdf", Type: "object"},
			{FlagName: "devices.sdg", JSONPath: "devices.sdg", Type: "object"},
			{FlagName: "devices.sdh", JSONPath: "devices.sdh", Type: "object"},
			{FlagName: "helpers.devtmpfs-automount", JSONPath: "helpers.devtmpfs_automount", Type: "boolean"},
			{FlagName: "helpers.distro", JSONPath: "helpers.distro", Type: "boolean"},
			{FlagName: "helpers.modules-dep", JSONPath: "helpers.modules_dep", Type: "boolean"},
			{FlagName: "helpers.network", JSONPath: "helpers.network", Type: "boolean"},
			{FlagName: "helpers.updatedb-disabled", JSONPath: "helpers.updatedb_disabled", Type: "boolean"},
			{FlagName: "id", JSONPath: "id", Type: "integer"},
			{FlagName: "interfaces", JSONPath: "interfaces", Type: "array"},
			{FlagName: "kernel", JSONPath: "kernel", Type: "string"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "memory-limit", JSONPath: "memory_limit", Type: "integer"},
			{FlagName: "root-device", JSONPath: "root_device", Type: "string"},
			{FlagName: "run-level", JSONPath: "run_level", Type: "string"},
			{FlagName: "virt-mode", JSONPath: "virt_mode", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	configurationProfilesPutLinodeConfigCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = configurationProfilesPutLinodeConfigCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = configurationProfilesPutLinodeConfigCmd.MarkFlagRequired("api-version")
	configurationProfilesPutLinodeConfigCmd.Flags().String("linode-id", "", "The `id` of the Linode.")
	_ = configurationProfilesPutLinodeConfigCmd.MarkFlagRequired("linode-id")
	configurationProfilesPutLinodeConfigCmd.Flags().String("config-id", "", "The `id` of the Configuration Profile.")
	_ = configurationProfilesPutLinodeConfigCmd.MarkFlagRequired("config-id")
	configurationProfilesPutLinodeConfigCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	configurationProfilesPutLinodeConfigCmd.Flags().String("comments", "", "Optional field for arbitrary user comments on this configuration.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("devices.sda", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("devices.sdb", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("devices.sdc", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("devices.sdd", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("devices.sde", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("devices.sdf", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("devices.sdg", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("devices.sdh", "", "Device can be either a Disk or Volume identified by `disk_id` or `volume_id`. Only one type per slot allowed. Can be `null`. Devices mapped from _sde_ through _sdh_ are unavailable in `fullvirt` virt_mode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("helpers.devtmpfs-automount", "false", "Populates the `/dev` directory early during boot without `udev`. Defaults to `false`.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("helpers.distro", "", "Helps maintain correct `inittab` or `upstart` console device.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("helpers.modules-dep", "", "Creates a modules dependency file for the kernel you run.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("helpers.network", "", "Set to `true` to automatically configure static networking. The `network` option applies only to legacy configuration profile interfaces and does not apply to [Linode interfaces](https://techdocs.akamai.com/linode-api/reference/post-linode-interface).")
	configurationProfilesPutLinodeConfigCmd.Flags().String("helpers.updatedb-disabled", "", "Set to `true` to disable the `updatedb` cron job to avoid disk thrashing.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("id", "", "__Read-only__ The ID of this Config.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("interfaces", "", "`interfaces` is applicable only to legacy configuration profiles and does not apply to [Linode interfaces](https://techdocs.akamai.com/linode-api/reference/post-linode-interface). From one to three network interfaces to add to this Linode's configuration profile. The position in the array determines which of the Linode's network interfaces is configured: - First [0]: `eth0` - Second [1]: `eth1` - Third [2]: `eth2` When updating a Linode's legacy interfaces, _each interface must be redefined_. An empty `interfaces` array results in a default `public` type interface configuration only. If no public Interface is configured, public IP addresses are still assigned to the Linode but will not be usable without manual configuration. > blue-book > > Changes to Linode Interface configurations can be enabled by rebooting the Linode. `vpc` details See the [VPC documentation](https://www.linode.com/docs/products/networking/vpc/#technical-specifications) guide for its specifications and limitations. `vlan` details - Only Next Generation Network (NGN) data centers support VLANs. Run the [List regions](https://techdocs.akamai.com/linode-api/reference/get-regions) operation to view the capabilities of data center regions. If a VLAN is attached to your Linode and you attempt to migrate or clone it to a non-NGN data center, the migration or cloning will not initiate. If a Linode cannot be migrated or cloned because of an incompatibility, you will be prompted to select a different data center or contact support. - See the [VLANs Overview](https://www.linode.com/docs/products/networking/vlans/#technical-specifications) guide to view additional specifications and limitations.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("kernel", "linode/latest-64bit", "The ID of the kernel used to boot a Linode. Run the [List kernels](https://techdocs.akamai.com/linode-api/reference/get-kernels) operation to see all available kernels. Here are some commonly used kernels: - `linode/latest-64bit`. This is the default, our latest kernel at the time of an instance boot or reboot. - `linode/grub2`. The upstream distribution-supplied kernel that's installed on the primary disk, or a custom kernel if installed. - `linode/direct-disk`. The master boot record (MBR) of the primary disk or root device. Use this in place of a Linux kernel.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("label", "", "__Filterable__ The name of the configuration for display in Akamai Cloud Manager.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("memory-limit", "", "Defaults to the total RAM of the Linode.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("root-device", "", "The root device to boot. > blue-book - If you leave this empty or set an invalid value, the root device defaults to `/dev/sda`. - If you specify a device at the root device location and it's not mounted, the Linode won't boot until a device is mounted.")
	configurationProfilesPutLinodeConfigCmd.Flags().String("run-level", "", "Defines the state of your Linode after booting. Defaults to `default`.")
	_ = configurationProfilesPutLinodeConfigCmd.RegisterFlagCompletionFunc("run-level", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"default", "single", "binbash"}, cobra.ShellCompDirectiveNoFileComp
	})
	configurationProfilesPutLinodeConfigCmd.Flags().String("virt-mode", "", "Controls the virtualization mode. Defaults to `paravirt`. - `paravirt` is suitable for most cases. Linodes running in `paravirt` mode share some qualities with the host, ultimately making it run faster since there is less transition between it and the host. - `fullvirt` affords more customization, but is slower because 100% of the VM is virtualized.")
	_ = configurationProfilesPutLinodeConfigCmd.RegisterFlagCompletionFunc("virt-mode", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"paravirt", "fullvirt"}, cobra.ShellCompDirectiveNoFileComp
	})
}
