// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var configurationProfileInterfacesPutLinodeConfigInterfaceCmd = &cobra.Command{
	Use:   "put-linode-config-interface",
	Short: "Update a configuration profile interface",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/configs/{configId}/interfaces/{interfaceId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)
		configIdVal, _ := cmd.Flags().GetString("config-id")
		if configIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "config-id")
		}
		path = strings.Replace(path, "{configId}", configIdVal, 1)
		interfaceIdVal, _ := cmd.Flags().GetString("interface-id")
		if interfaceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "interface-id")
		}
		path = strings.Replace(path, "{interfaceId}", interfaceIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "ip-ranges", JSONPath: "ip_ranges", Type: "array"},
			{FlagName: "ipv4.nat-1-1", JSONPath: "ipv4.nat_1_1", Type: "string"},
			{FlagName: "ipv4.vpc", JSONPath: "ipv4.vpc", Type: "string"},
			{FlagName: "primary", JSONPath: "primary", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = configurationProfileInterfacesPutLinodeConfigInterfaceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = configurationProfileInterfacesPutLinodeConfigInterfaceCmd.MarkFlagRequired("api-version")
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("linode-id", "", "The `id` of the Linode.")
	_ = configurationProfileInterfacesPutLinodeConfigInterfaceCmd.MarkFlagRequired("linode-id")
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("config-id", "", "The `id` of the Configuration Profile.")
	_ = configurationProfileInterfacesPutLinodeConfigInterfaceCmd.MarkFlagRequired("config-id")
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("interface-id", "", "The `id` of the Linode Configuration Profile Interface.")
	_ = configurationProfileInterfacesPutLinodeConfigInterfaceCmd.MarkFlagRequired("interface-id")
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("ip-ranges", "", "IPv4 CIDR VPC subnet ranges that are routed to this interface. - A range can't include any addresses that are assigned to an active Linode or another VPC subnet. - When updating, you need to include any existing ranges to maintain them. If a range is left out, it will be removed. - Include this as an empty array (`[]`) to remove all existing values. - Omit this array to leave all existing `ip_ranges` as is. <<LB>> > blue-book > > This only applies to interfaces with a `purpose` of `vpc`.")
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("ipv4.nat-1-1", "", "The 1:1 NAT IPv4 address, used to associate a public IPv4 address with the interface's VPC subnet IPv4 address. - You can set this to a specific, public IPv4 address that's available on the Linode. You can also use the `any` keyword to enable the Linode's assigned public IPv4 address. - A specified address can't be used on another Linode. - Include this as an empty object (`\"\"`) to remove an existing `nat_1_1` value. - Omit this object or include it and set it to `null` to leave an existing `nat_1_1` value as is.")
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("ipv4.vpc", "", "The VPC subnet IPv4 address for this interface. - The `vpc` can't be assigned to an existing Linode as an address or in a range. - The target address can't be the first two or last two addresses in the subnet IPv4 range. - If omitted, a valid address within the subnet IPv4 range is automatically assigned.")
	configurationProfileInterfacesPutLinodeConfigInterfaceCmd.Flags().String("primary", "", "Set to `true` to label this configuration profile interface as the default route to the Linode. - Each Linode can have one interface set as its `primary`. - If you don't specifically set a `primary`, the first non-`vlan` type interface is automatically treated as the primary.")
}
