// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var delegationForParentAndChildAccountsPutIamDelegationChildAccountUsersCmd = &cobra.Command{
	Use:   "put-iam-delegation-child-account-users",
	Short: "Update the account delegation for a child account",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/iam/delegation/child-accounts/{euuid}/users"
		euuidVal, _ := cmd.Flags().GetString("euuid")
		if euuidVal == "" {
			return fmt.Errorf("required flag --%s not set", "euuid")
		}
		path = strings.Replace(path, "{euuid}", euuidVal, 1)
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "users", JSONPath: "users", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	delegationForParentAndChildAccountsPutIamDelegationChildAccountUsersCmd.Flags().String("euuid", "", "A unique identifier for a child account. To get this value, run [List child accounts](https://techdocs.akamai.com/linode-api/reference/get-iam-delegation-all-child-accounts).")
	_ = delegationForParentAndChildAccountsPutIamDelegationChildAccountUsersCmd.MarkFlagRequired("euuid")
	delegationForParentAndChildAccountsPutIamDelegationChildAccountUsersCmd.Flags().String("api-version", "", "__Enum__ Call the `v4` URL.")
	_ = delegationForParentAndChildAccountsPutIamDelegationChildAccountUsersCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = delegationForParentAndChildAccountsPutIamDelegationChildAccountUsersCmd.MarkFlagRequired("api-version")
	delegationForParentAndChildAccountsPutIamDelegationChildAccountUsersCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	delegationForParentAndChildAccountsPutIamDelegationChildAccountUsersCmd.Flags().String("users", "", "Usernames to add to the account delegation for the child account.")
}
