// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var eventsPostEventSeenCmd = &cobra.Command{
	Use:   "post-event-seen",
	Short: "Mark an event as seen",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/events/{eventId}/seen"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		eventIdVal, _ := cmd.Flags().GetString("event-id")
		if eventIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "event-id")
		}
		path = strings.Replace(path, "{eventId}", eventIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("POST", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	eventsPostEventSeenCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = eventsPostEventSeenCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = eventsPostEventSeenCmd.MarkFlagRequired("api-version")
	eventsPostEventSeenCmd.Flags().String("event-id", "", "The ID of the Event to designate as seen.")
	_ = eventsPostEventSeenCmd.MarkFlagRequired("event-id")
}
