// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var firewallsGetFirewallRuleVersionCmd = &cobra.Command{
	Use:   "get-firewall-rule-version",
	Short: "Get a firewall rule version",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/networking/firewalls/{firewallId}/history/rules/{version}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		firewallIdVal, _ := cmd.Flags().GetString("firewall-id")
		if firewallIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "firewall-id")
		}
		path = strings.Replace(path, "{firewallId}", firewallIdVal, 1)
		versionVal, _ := cmd.Flags().GetString("version")
		if versionVal == "" {
			return fmt.Errorf("required flag --%s not set", "version")
		}
		path = strings.Replace(path, "{version}", versionVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	firewallsGetFirewallRuleVersionCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = firewallsGetFirewallRuleVersionCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = firewallsGetFirewallRuleVersionCmd.MarkFlagRequired("api-version")
	firewallsGetFirewallRuleVersionCmd.Flags().String("firewall-id", "", "ID of the Firewall to access.")
	_ = firewallsGetFirewallRuleVersionCmd.MarkFlagRequired("firewall-id")
	firewallsGetFirewallRuleVersionCmd.Flags().String("version", "", "The firewall rule version to view.")
	_ = firewallsGetFirewallRuleVersionCmd.MarkFlagRequired("version")
}
