// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var generalGetDatabasesEngineCmd = &cobra.Command{
	Use:   "get-databases-engine",
	Short: "Get a Managed Databases engine",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/engines/{engineId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		engineIdVal, _ := cmd.Flags().GetString("engine-id")
		if engineIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "engine-id")
		}
		path = strings.Replace(path, "{engineId}", engineIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	generalGetDatabasesEngineCmd.Flags().String("page", "1", "The page of a collection to return.")
	generalGetDatabasesEngineCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	generalGetDatabasesEngineCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = generalGetDatabasesEngineCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = generalGetDatabasesEngineCmd.MarkFlagRequired("api-version")
	generalGetDatabasesEngineCmd.Flags().String("engine-id", "", "The ID of the Managed Database engine.")
	_ = generalGetDatabasesEngineCmd.MarkFlagRequired("engine-id")
}
