// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var idpConfigurationGetIdpConfigCertificatesCmd = &cobra.Command{
	Use:   "get-idp-config-certificates",
	Short: "List IDP certificates",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/iam/idp-configs/{idpConfigId}/certificates"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		idpConfigIdVal, _ := cmd.Flags().GetString("idp-config-id")
		if idpConfigIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "idp-config-id")
		}
		path = strings.Replace(path, "{idpConfigId}", idpConfigIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("page"); v != "" {
			params["page"] = v
		}
		if v, _ := cmd.Flags().GetString("page-size"); v != "" {
			params["page_size"] = v
		}
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	idpConfigurationGetIdpConfigCertificatesCmd.Flags().String("page", "1", "The page of a collection to return.")
	idpConfigurationGetIdpConfigCertificatesCmd.Flags().String("page-size", "100", "The number of items to return per page.")
	idpConfigurationGetIdpConfigCertificatesCmd.Flags().String("api-version", "", "__Enum__ Call the `v4beta` URL for operations still only in beta.")
	_ = idpConfigurationGetIdpConfigCertificatesCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = idpConfigurationGetIdpConfigCertificatesCmd.MarkFlagRequired("api-version")
	idpConfigurationGetIdpConfigCertificatesCmd.Flags().String("idp-config-id", "", "The unique identifier of the external identity provider configuration. This is the `id` value returned by the [List IDP configurations](https://techdocs.akamai.com/linode-api/reference/get-idp-configs) operation.")
	_ = idpConfigurationGetIdpConfigCertificatesCmd.MarkFlagRequired("idp-config-id")
}
