// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var imageSharingPutSharegroupCmd = &cobra.Command{
	Use:   "put-sharegroup",
	Short: "Update a share group",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/images/sharegroups/{sharegroupId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		sharegroupIdVal, _ := cmd.Flags().GetString("sharegroup-id")
		if sharegroupIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "sharegroup-id")
		}
		path = strings.Replace(path, "{sharegroupId}", sharegroupIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "description", JSONPath: "description", Type: "string"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	imageSharingPutSharegroupCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = imageSharingPutSharegroupCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = imageSharingPutSharegroupCmd.MarkFlagRequired("api-version")
	imageSharingPutSharegroupCmd.Flags().String("sharegroup-id", "", "The share group's unique identifier assigned after creating it. Not to be confused with the group's `uuid`.")
	_ = imageSharingPutSharegroupCmd.MarkFlagRequired("sharegroup-id")
	imageSharingPutSharegroupCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	imageSharingPutSharegroupCmd.Flags().String("description", "", "A detailed description of this share group.")
	imageSharingPutSharegroupCmd.Flags().String("label", "", "The share group's descriptive name.")
}
