// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var imagesDeleteImageCmd = &cobra.Command{
	Use:   "delete-image",
	Short: "Delete an image",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/images/{imageId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		imageIdVal, _ := cmd.Flags().GetString("image-id")
		if imageIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "image-id")
		}
		path = strings.Replace(path, "{imageId}", imageIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	imagesDeleteImageCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = imagesDeleteImageCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = imagesDeleteImageCmd.MarkFlagRequired("api-version")
	imagesDeleteImageCmd.Flags().String("image-id", "", "The unique identifier assigned to the image after creation.")
	_ = imagesDeleteImageCmd.MarkFlagRequired("image-id")
}
