// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var imageSharingDeleteSharegroupCmd = &cobra.Command{
	Use:   "delete-sharegroup",
	Short: "Delete a share group",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/images/sharegroups/{sharegroupId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		sharegroupIdVal, _ := cmd.Flags().GetString("sharegroup-id")
		if sharegroupIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "sharegroup-id")
		}
		path = strings.Replace(path, "{sharegroupId}", sharegroupIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	imageSharingDeleteSharegroupCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = imageSharingDeleteSharegroupCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = imageSharingDeleteSharegroupCmd.MarkFlagRequired("api-version")
	imageSharingDeleteSharegroupCmd.Flags().String("sharegroup-id", "", "The share group's unique identifier assigned after creating it. Not to be confused with the group's `uuid`.")
	_ = imageSharingDeleteSharegroupCmd.MarkFlagRequired("sharegroup-id")
}
