// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var imageSharingPostSharegroupImagesCmd = &cobra.Command{
	Use:   "post-sharegroup-images",
	Short: "Add images to a share group",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/images/sharegroups/{sharegroupId}/images"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		sharegroupIdVal, _ := cmd.Flags().GetString("sharegroup-id")
		if sharegroupIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "sharegroup-id")
		}
		path = strings.Replace(path, "{sharegroupId}", sharegroupIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "images", JSONPath: "images", Type: "array"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	imageSharingPostSharegroupImagesCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = imageSharingPostSharegroupImagesCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = imageSharingPostSharegroupImagesCmd.MarkFlagRequired("api-version")
	imageSharingPostSharegroupImagesCmd.Flags().String("sharegroup-id", "", "The share group's unique identifier assigned after creating it. Not to be confused with the group's `uuid`.")
	_ = imageSharingPostSharegroupImagesCmd.MarkFlagRequired("sharegroup-id")
	imageSharingPostSharegroupImagesCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	imageSharingPostSharegroupImagesCmd.Flags().String("images", "", "")
	_ = imageSharingPostSharegroupImagesCmd.MarkFlagRequired("images")
}
