// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var ipAddressesPutIpCmd = &cobra.Command{
	Use:   "put-ip",
	Short: "Update an IP address's RDNS",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/networking/ips/{address}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		addressVal, _ := cmd.Flags().GetString("address")
		if addressVal == "" {
			return fmt.Errorf("required flag --%s not set", "address")
		}
		path = strings.Replace(path, "{address}", addressVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "rdns", JSONPath: "rdns", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	ipAddressesPutIpCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = ipAddressesPutIpCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = ipAddressesPutIpCmd.MarkFlagRequired("api-version")
	ipAddressesPutIpCmd.Flags().String("address", "", "The address to operate on.")
	_ = ipAddressesPutIpCmd.MarkFlagRequired("address")
	ipAddressesPutIpCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	ipAddressesPutIpCmd.Flags().String("rdns", "", "The reverse DNS assigned to this address. For public IPv4 addresses, this will be set to a default value provided by Linode if not explicitly set.")
	_ = ipAddressesPutIpCmd.MarkFlagRequired("rdns")
}
