// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var linodeFirewallsCmd = &cobra.Command{
	Use:   "linode-firewalls",
	Short: "linode-firewalls operations",
}
