// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var linodeInstancesPostRebootLinodeInstanceCmd = &cobra.Command{
	Use:   "post-reboot-linode-instance",
	Short: "Reboot a Linode",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/reboot"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "config-id", JSONPath: "config_id", Type: "integer"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeInstancesPostRebootLinodeInstanceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeInstancesPostRebootLinodeInstanceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeInstancesPostRebootLinodeInstanceCmd.MarkFlagRequired("api-version")
	linodeInstancesPostRebootLinodeInstanceCmd.Flags().String("linode-id", "", "ID of the linode to reboot.")
	_ = linodeInstancesPostRebootLinodeInstanceCmd.MarkFlagRequired("linode-id")
	linodeInstancesPostRebootLinodeInstanceCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	linodeInstancesPostRebootLinodeInstanceCmd.Flags().String("config-id", "", "The Linode Config ID to reboot into. If `null` or omitted, the last booted config will be used. If there was no last booted config and this Linode only has one config, it will be used. If a config cannot be determined, an error will be returned.")
}
