// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var linodeDisksGetLinodeDiskCmd = &cobra.Command{
	Use:   "get-linode-disk",
	Short: "Get a disk",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/instances/{linodeId}/disks/{diskId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		linodeIdVal, _ := cmd.Flags().GetString("linode-id")
		if linodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "linode-id")
		}
		path = strings.Replace(path, "{linodeId}", linodeIdVal, 1)
		diskIdVal, _ := cmd.Flags().GetString("disk-id")
		if diskIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "disk-id")
		}
		path = strings.Replace(path, "{diskId}", diskIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	linodeDisksGetLinodeDiskCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = linodeDisksGetLinodeDiskCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = linodeDisksGetLinodeDiskCmd.MarkFlagRequired("api-version")
	linodeDisksGetLinodeDiskCmd.Flags().String("linode-id", "", "ID of the Linode to look up.")
	_ = linodeDisksGetLinodeDiskCmd.MarkFlagRequired("linode-id")
	linodeDisksGetLinodeDiskCmd.Flags().String("disk-id", "", "ID of the Disk to look up.")
	_ = linodeDisksGetLinodeDiskCmd.MarkFlagRequired("disk-id")
}
