// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var lkeClustersPostLkeClusterRegenerateCmd = &cobra.Command{
	Use:   "post-lke-cluster-regenerate",
	Short: "Regenerate a Kubernetes cluster",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/lke/clusters/{clusterId}/regenerate"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		clusterIdVal, _ := cmd.Flags().GetString("cluster-id")
		if clusterIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "cluster-id")
		}
		path = strings.Replace(path, "{clusterId}", clusterIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "kubeconfig", JSONPath: "kubeconfig", Type: "boolean"},
			{FlagName: "servicetoken", JSONPath: "servicetoken", Type: "boolean"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	lkeClustersPostLkeClusterRegenerateCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = lkeClustersPostLkeClusterRegenerateCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = lkeClustersPostLkeClusterRegenerateCmd.MarkFlagRequired("api-version")
	lkeClustersPostLkeClusterRegenerateCmd.Flags().String("cluster-id", "", "ID of the target Kubernetes cluster.")
	_ = lkeClustersPostLkeClusterRegenerateCmd.MarkFlagRequired("cluster-id")
	lkeClustersPostLkeClusterRegenerateCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	lkeClustersPostLkeClusterRegenerateCmd.Flags().String("kubeconfig", "false", "Whether to delete and regenerate the Kubeconfig file for this Cluster.")
	lkeClustersPostLkeClusterRegenerateCmd.Flags().String("servicetoken", "false", "Whether to delete and regenerate the service access token for this Cluster.")
}
