// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var lkeApiEndpointsGetLkeClusterApiEndpointsCmd = &cobra.Command{
	Use:   "get-lke-cluster-api-endpoints",
	Short: "List Kubernetes API endpoints",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/lke/clusters/{clusterId}/api-endpoints"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		clusterIdVal, _ := cmd.Flags().GetString("cluster-id")
		if clusterIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "cluster-id")
		}
		path = strings.Replace(path, "{clusterId}", clusterIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	lkeApiEndpointsGetLkeClusterApiEndpointsCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = lkeApiEndpointsGetLkeClusterApiEndpointsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = lkeApiEndpointsGetLkeClusterApiEndpointsCmd.MarkFlagRequired("api-version")
	lkeApiEndpointsGetLkeClusterApiEndpointsCmd.Flags().String("cluster-id", "", "ID of the Kubernetes cluster to look up.")
	_ = lkeApiEndpointsGetLkeClusterApiEndpointsCmd.MarkFlagRequired("cluster-id")
}
