// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var logsDeleteDestinationCmd = &cobra.Command{
	Use:   "delete-destination",
	Short: "Delete a destination",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/monitor/streams/destinations/{destinationId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		destinationIdVal, _ := cmd.Flags().GetString("destination-id")
		if destinationIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "destination-id")
		}
		path = strings.Replace(path, "{destinationId}", destinationIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	logsDeleteDestinationCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = logsDeleteDestinationCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = logsDeleteDestinationCmd.MarkFlagRequired("api-version")
	logsDeleteDestinationCmd.Flags().String("destination-id", "", "The unique identifier assigned to the logs destination. Run the [List destinations](https://techdocs.akamai.com/linode-api/reference/get-destinations) operation and store the `id` for the applicable one.")
	_ = logsDeleteDestinationCmd.MarkFlagRequired("destination-id")
}
