// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var longviewClientsDeleteLongviewClientCmd = &cobra.Command{
	Use:   "delete-longview-client",
	Short: "Delete a Longview client",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/longview/clients/{clientId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		clientIdVal, _ := cmd.Flags().GetString("client-id")
		if clientIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "client-id")
		}
		path = strings.Replace(path, "{clientId}", clientIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	longviewClientsDeleteLongviewClientCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = longviewClientsDeleteLongviewClientCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = longviewClientsDeleteLongviewClientCmd.MarkFlagRequired("api-version")
	longviewClientsDeleteLongviewClientCmd.Flags().String("client-id", "", "The Longview Client ID to access.")
	_ = longviewClientsDeleteLongviewClientCmd.MarkFlagRequired("client-id")
}
