// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var managedIssuesGetManagedIssueCmd = &cobra.Command{
	Use:   "get-managed-issue",
	Short: "Get a managed issue",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/managed/issues/{issueId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		issueIdVal, _ := cmd.Flags().GetString("issue-id")
		if issueIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "issue-id")
		}
		path = strings.Replace(path, "{issueId}", issueIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	managedIssuesGetManagedIssueCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = managedIssuesGetManagedIssueCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = managedIssuesGetManagedIssueCmd.MarkFlagRequired("api-version")
	managedIssuesGetManagedIssueCmd.Flags().String("issue-id", "", "The Issue to look up.")
	_ = managedIssuesGetManagedIssueCmd.MarkFlagRequired("issue-id")
}
