// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var managedServiceMonitorsPutManagedServiceCmd = &cobra.Command{
	Use:   "put-managed-service",
	Short: "Update a managed service monitor",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/managed/services/{serviceId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		serviceIdVal, _ := cmd.Flags().GetString("service-id")
		if serviceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "service-id")
		}
		path = strings.Replace(path, "{serviceId}", serviceIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "address", JSONPath: "address", Type: "string"},
			{FlagName: "body", JSONPath: "body", Type: "string"},
			{FlagName: "consultation-group", JSONPath: "consultation_group", Type: "string"},
			{FlagName: "created", JSONPath: "created", Type: "string"},
			{FlagName: "credentials", JSONPath: "credentials", Type: "array"},
			{FlagName: "id", JSONPath: "id", Type: "integer"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "notes", JSONPath: "notes", Type: "string"},
			{FlagName: "region", JSONPath: "region", Type: "string"},
			{FlagName: "service-type", JSONPath: "service_type", Type: "string"},
			{FlagName: "status", JSONPath: "status", Type: "string"},
			{FlagName: "timeout", JSONPath: "timeout", Type: "integer"},
			{FlagName: "updated", JSONPath: "updated", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = managedServiceMonitorsPutManagedServiceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = managedServiceMonitorsPutManagedServiceCmd.MarkFlagRequired("api-version")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("service-id", "", "The ID of the Managed Service to access.")
	_ = managedServiceMonitorsPutManagedServiceCmd.MarkFlagRequired("service-id")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("address", "", "The URL at which this Service is monitored. URL parameters such as `?no-cache=1` are preserved. URL fragments/anchors such as `#monitor` are __not__ preserved.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("body", "", "What to expect to find in the response body for the Service to be considered up.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("consultation-group", "", "The group of ManagedContacts who should be notified or consulted with when an Issue is detected.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("created", "", "__Read-only__ When this Managed Service was created.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("credentials", "", "An array of ManagedCredential IDs that should be used when attempting to resolve issues with this Service.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("id", "", "__Read-only__ This Service's unique ID.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("label", "", "The label for this Service. This is for display purposes only.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("notes", "", "Any information relevant to the Service that Linode special forces should know when attempting to resolve Issues.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("region", "", "The Region in which this Service is located. This is required if address is a private IP, and may not be set otherwise.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("service-type", "", "How this Service is monitored.")
	_ = managedServiceMonitorsPutManagedServiceCmd.RegisterFlagCompletionFunc("service-type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"url", "tcp"}, cobra.ShellCompDirectiveNoFileComp
	})
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("status", "", "__Read-only__ The current status of this Service.")
	_ = managedServiceMonitorsPutManagedServiceCmd.RegisterFlagCompletionFunc("status", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"disabled", "pending", "ok", "problem"}, cobra.ShellCompDirectiveNoFileComp
	})
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("timeout", "", "How long to wait, in seconds, for a response before considering the Service to be down.")
	managedServiceMonitorsPutManagedServiceCmd.Flags().String("updated", "", "__Read-only__ When this Managed Service was last updated.")
}
