// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var managedContactsCmd = &cobra.Command{
	Use:   "managed-contacts",
	Short: "managed-contacts operations",
}
