// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var managedSshKeysCmd = &cobra.Command{
	Use:   "managed-ssh-keys",
	Short: "managed-ssh-keys operations",
}
