// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var mysqlPutDatabasesMysqlInstanceCmd = &cobra.Command{
	Use:   "put-databases-mysql-instance",
	Short: "Update a MySQL Managed Database",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/mysql/instances/{mysqlInstanceId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		mysqlInstanceIdVal, _ := cmd.Flags().GetString("mysql-instance-id")
		if mysqlInstanceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "mysql-instance-id")
		}
		path = strings.Replace(path, "{mysqlInstanceId}", mysqlInstanceIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "allow-list", JSONPath: "allow_list", Type: "array"},
			{FlagName: "engine-config.binlog-retention-period", JSONPath: "engine_config.binlog_retention_period", Type: "integer"},
			{FlagName: "engine-config.mysql", JSONPath: "engine_config.mysql", Type: "object"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "private-network.public-access", JSONPath: "private_network.public_access", Type: "boolean"},
			{FlagName: "private-network.subnet-id", JSONPath: "private_network.subnet_id", Type: "integer"},
			{FlagName: "private-network.vpc-id", JSONPath: "private_network.vpc_id", Type: "integer"},
			{FlagName: "type", JSONPath: "type", Type: "string"},
			{FlagName: "updates.day-of-week", JSONPath: "updates.day_of_week", Type: "integer"},
			{FlagName: "updates.duration", JSONPath: "updates.duration", Type: "integer"},
			{FlagName: "updates.frequency", JSONPath: "updates.frequency", Type: "string"},
			{FlagName: "updates.hour-of-day", JSONPath: "updates.hour_of_day", Type: "integer"},
			{FlagName: "updates.pending", JSONPath: "updates.pending", Type: "array"},
			{FlagName: "version", JSONPath: "version", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = mysqlPutDatabasesMysqlInstanceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = mysqlPutDatabasesMysqlInstanceCmd.MarkFlagRequired("api-version")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("mysql-instance-id", "", "The unique identifier for a MySQL Managed Database. Run the [List MySQL Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-mysql-instances) operation and store the `id` for the desired one.")
	_ = mysqlPutDatabasesMysqlInstanceCmd.MarkFlagRequired("mysql-instance-id")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("allow-list", "", "Controls access to the Managed Database. - Individually included IP addresses or CIDR ranges can access the Managed Database while all other sources are blocked. - A standalone value of `0.0.0.0/0` allows all IP addresses access to the Managed Database. - An empty array (`[]`) blocks all public and private connections to the Managed Database.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("engine-config.binlog-retention-period", "", "The minimum amount of time in seconds to keep `binlog` entries before deletion. This may be extended for services that require `binlog` entries for longer than the default, for example if using the MySQL Debezium Kafka connector.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("engine-config.mysql", "", "MySQL-specific advanced configuration parameters.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("label", "", "__Filterable__ A name used to identify the Managed Database. This needs to be unique per Managed Database `engine` type. For example, you could use `database_1`, `database_2`, and `database_3` for three unique MySQL Managed Databases. You can also use these same names for three unique PostgreSQL Managed Databases. However, you can't repeat any of these names for either engine type.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("private-network.public-access", "false", "Set to `true` to allow clients outside of the VPC to connect to the database using a public IP address. Defaults to `false`, where only nodes within the specified `vpc_id` can access the Managed Database cluster. > blue-book > > If your Managed Database is also configured using an `allow_list`, only IP addresses set in it can access that database, even if this object is set to `true`.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("private-network.subnet-id", "", "If the `vpc_id` includes multiple subnets, specify the `subnet_id` you want to use to control access to the database. Use the [List VPCs](https://techdocs.akamai.com/linode-api/reference/get-vpcs) operation to find and store the `id` of the relevant subnet object. > blue-book > > A VPC needs at least one subnet to assign a Manage Database instance.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("private-network.vpc-id", "", "The unique identifier of the VPC you want to use to enable private access to the Managed Database. Run the [List VPCs](https://techdocs.akamai.com/linode-api/reference/get-vpcs) operation and store the `id` for the applicable VPC.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("type", "", "Request re-sizing of your cluster to a Linode Type with more disk space. For example, you could request a Linode Type that uses a higher plan. - Needs to be a Linode Type with more disk space than your current Linode. - Resizing to a larger Linode Type can accrue additional cost. Review the `price` output in the [List types](https://techdocs.akamai.com/linode-api/reference/get-linode-types) operation for more information. - You can't update the `allow_list` and set a new `type` in the same request. - Any active updates to your cluster need to complete before you can request a resize. The reverse is also true: An active resizing needs to complete before you can perform any other update.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("updates.day-of-week", "", "The numeric reference for the day of the week to perform maintenance. `1` is Monday, `2` is Tuesday, through to `7` which is Sunday.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("updates.duration", "", "The maximum maintenance window time in hours.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("updates.frequency", "weekly", "How frequently maintenance occurs. Currently can only be `weekly`.")
	_ = mysqlPutDatabasesMysqlInstanceCmd.RegisterFlagCompletionFunc("updates.frequency", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"weekly"}, cobra.ShellCompDirectiveNoFileComp
	})
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("updates.hour-of-day", "", "The hour to begin maintenance based in UTC time.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("updates.pending", "", "__Read-only__ An array of pending updates.")
	mysqlPutDatabasesMysqlInstanceCmd.Flags().String("version", "", "__Filterable__ The Managed Database engine version.")
}
