// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var mysqlPostDatabasesMysqlInstancesCmd = &cobra.Command{
	Use:   "post-databases-mysql-instances",
	Short: "Create or restore a MySQL Managed Database",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/mysql/instances"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "allow-list", JSONPath: "allow_list", Type: "array"},
			{FlagName: "cluster-size", JSONPath: "cluster_size", Type: "integer"},
			{FlagName: "engine", JSONPath: "engine", Type: "string"},
			{FlagName: "engine-config.binlog-retention-period", JSONPath: "engine_config.binlog_retention_period", Type: "integer"},
			{FlagName: "engine-config.mysql", JSONPath: "engine_config.mysql", Type: "object"},
			{FlagName: "fork.restore-time", JSONPath: "fork.restore_time", Type: "string"},
			{FlagName: "fork.source", JSONPath: "fork.source", Type: "integer"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "private-network.public-access", JSONPath: "private_network.public_access", Type: "boolean"},
			{FlagName: "private-network.subnet-id", JSONPath: "private_network.subnet_id", Type: "integer"},
			{FlagName: "private-network.vpc-id", JSONPath: "private_network.vpc_id", Type: "integer"},
			{FlagName: "region", JSONPath: "region", Type: "string"},
			{FlagName: "ssl-connection", JSONPath: "ssl_connection", Type: "boolean"},
			{FlagName: "type", JSONPath: "type", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = mysqlPostDatabasesMysqlInstancesCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = mysqlPostDatabasesMysqlInstancesCmd.MarkFlagRequired("api-version")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("allow-list", "", "Controls access to the Managed Database. - Individually included IP addresses or CIDR ranges can access the Managed Database while all other sources are blocked. - A standalone value of `0.0.0.0/0` allows all IP addresses access to the Managed Database. - An empty array (`[]`) blocks all public and private connections to the Managed Database.")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("cluster-size", "1", "The number of Linode instance nodes deployed to the Managed Database, from `1` to `3`. Consider these points when setting a `cluster_size`: - Choose `3` nodes to create a high availability cluster that consists of one `primary` node and two `standby` nodes. - A `2` node cluster is only available with a dedicated plan. It consists of one `primary` node and one `standby` node.")
	_ = mysqlPostDatabasesMysqlInstancesCmd.RegisterFlagCompletionFunc("cluster-size", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"1", "2", "3"}, cobra.ShellCompDirectiveNoFileComp
	})
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("engine", "", "The Managed Database engine in engine/version format.")
	_ = mysqlPostDatabasesMysqlInstancesCmd.MarkFlagRequired("engine")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("engine-config.binlog-retention-period", "", "The minimum amount of time in seconds to keep `binlog` entries before deletion. This may be extended for services that require `binlog` entries for longer than the default, for example if using the MySQL Debezium Kafka connector.")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("engine-config.mysql", "", "MySQL-specific advanced configuration parameters.")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("fork.restore-time", "", "A specific database timestamp to restore from.")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("fork.source", "", "The unique instance id for the database to fork from. Run the [List Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-instances) operation and store the unique `id` for the target Managed Database.")
	_ = mysqlPostDatabasesMysqlInstancesCmd.MarkFlagRequired("fork.source")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("label", "", "__Filterable__ A name used to identify the Managed Database. This needs to be unique per Managed Database `engine` type. For example, you could use `database_1`, `database_2`, and `database_3` for three unique MySQL Managed Databases. You can also use these same names for three unique PostgreSQL Managed Databases. However, you can't repeat any of these names for either engine type.")
	_ = mysqlPostDatabasesMysqlInstancesCmd.MarkFlagRequired("label")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("private-network.public-access", "false", "Set to `true` to allow clients outside of the VPC to connect to the database using a public IP address. Defaults to `false`, where only nodes within the specified `vpc_id` can access the Managed Database cluster. > blue-book > > If your Managed Database is also configured using an `allow_list`, only IP addresses set in it can access that database, even if this object is set to `true`.")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("private-network.subnet-id", "", "If the `vpc_id` includes multiple subnets, specify the `subnet_id` you want to use to control access to the database. Use the [List VPCs](https://techdocs.akamai.com/linode-api/reference/get-vpcs) operation to find and store the `id` of the relevant subnet object. > blue-book > > A VPC needs at least one subnet to assign a Manage Database instance.")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("private-network.vpc-id", "", "The unique identifier of the VPC you want to use to enable private access to the Managed Database. Run the [List VPCs](https://techdocs.akamai.com/linode-api/reference/get-vpcs) operation and store the `id` for the applicable VPC.")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("region", "", "__Filterable__ The unique identifier for the [region](https://techdocs.akamai.com/linode-api/reference/get-regions) where the Managed Database lives.")
	_ = mysqlPostDatabasesMysqlInstancesCmd.MarkFlagRequired("region")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("ssl-connection", "true", "Currently required to be `true`. Whether to require SSL credentials to establish a connection to the Managed Database. Run the [Get managed MySQL database credentials](https://techdocs.akamai.com/linode-api/reference/get-databases-mysql-instance-credentials) operation for access information.")
	mysqlPostDatabasesMysqlInstancesCmd.Flags().String("type", "", "__Filterable__ The Linode Instance type used by the Managed Database for its nodes.")
	_ = mysqlPostDatabasesMysqlInstancesCmd.MarkFlagRequired("type")
}
