// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var mysqlDeleteDatabasesMysqlInstanceCmd = &cobra.Command{
	Use:   "delete-databases-mysql-instance",
	Short: "Delete a MySQL Managed Database",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/mysql/instances/{mysqlInstanceId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		mysqlInstanceIdVal, _ := cmd.Flags().GetString("mysql-instance-id")
		if mysqlInstanceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "mysql-instance-id")
		}
		path = strings.Replace(path, "{mysqlInstanceId}", mysqlInstanceIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	mysqlDeleteDatabasesMysqlInstanceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = mysqlDeleteDatabasesMysqlInstanceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = mysqlDeleteDatabasesMysqlInstanceCmd.MarkFlagRequired("api-version")
	mysqlDeleteDatabasesMysqlInstanceCmd.Flags().String("mysql-instance-id", "", "The unique identifier for a MySQL Managed Database. Run the [List MySQL Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-mysql-instances) operation and store the `id` for the desired one.")
	_ = mysqlDeleteDatabasesMysqlInstanceCmd.MarkFlagRequired("mysql-instance-id")
}
