// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var nodesGetNodeBalancerNodeCmd = &cobra.Command{
	Use:   "get-node-balancer-node",
	Short: "Get a NodeBalancer's node",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/nodebalancers/{nodeBalancerId}/configs/{configId}/nodes/{nodeId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		nodeBalancerIdVal, _ := cmd.Flags().GetString("node-balancer-id")
		if nodeBalancerIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "node-balancer-id")
		}
		path = strings.Replace(path, "{nodeBalancerId}", nodeBalancerIdVal, 1)
		configIdVal, _ := cmd.Flags().GetString("config-id")
		if configIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "config-id")
		}
		path = strings.Replace(path, "{configId}", configIdVal, 1)
		nodeIdVal, _ := cmd.Flags().GetString("node-id")
		if nodeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "node-id")
		}
		path = strings.Replace(path, "{nodeId}", nodeIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	nodesGetNodeBalancerNodeCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = nodesGetNodeBalancerNodeCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = nodesGetNodeBalancerNodeCmd.MarkFlagRequired("api-version")
	nodesGetNodeBalancerNodeCmd.Flags().String("node-balancer-id", "", "The ID of the NodeBalancer.")
	_ = nodesGetNodeBalancerNodeCmd.MarkFlagRequired("node-balancer-id")
	nodesGetNodeBalancerNodeCmd.Flags().String("config-id", "", "The ID of the Config to access.")
	_ = nodesGetNodeBalancerNodeCmd.MarkFlagRequired("config-id")
	nodesGetNodeBalancerNodeCmd.Flags().String("node-id", "", "The ID of the Node to access.")
	_ = nodesGetNodeBalancerNodeCmd.MarkFlagRequired("node-id")
}
