// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var oauthClientsPostResetClientSecretCmd = &cobra.Command{
	Use:   "post-reset-client-secret",
	Short: "Reset an OAuth client secret",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/oauth-clients/{clientId}/reset-secret"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		clientIdVal, _ := cmd.Flags().GetString("client-id")
		if clientIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "client-id")
		}
		path = strings.Replace(path, "{clientId}", clientIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("POST", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	oauthClientsPostResetClientSecretCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = oauthClientsPostResetClientSecretCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = oauthClientsPostResetClientSecretCmd.MarkFlagRequired("api-version")
	oauthClientsPostResetClientSecretCmd.Flags().String("client-id", "", "The OAuth Client ID to look up.")
	_ = oauthClientsPostResetClientSecretCmd.MarkFlagRequired("client-id")
}
