// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var oauthPreferencesCmd = &cobra.Command{
	Use:   "oauth-preferences",
	Short: "oauth-preferences operations",
}
