// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var paymentMethodsDeletePaymentMethodCmd = &cobra.Command{
	Use:   "delete-payment-method",
	Short: "Delete a payment method",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/payment-methods/{paymentMethodId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		paymentMethodIdVal, _ := cmd.Flags().GetString("payment-method-id")
		if paymentMethodIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "payment-method-id")
		}
		path = strings.Replace(path, "{paymentMethodId}", paymentMethodIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	paymentMethodsDeletePaymentMethodCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = paymentMethodsDeletePaymentMethodCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = paymentMethodsDeletePaymentMethodCmd.MarkFlagRequired("api-version")
	paymentMethodsDeletePaymentMethodCmd.Flags().String("payment-method-id", "", "The ID of the Payment Method to look up.")
	_ = paymentMethodsDeletePaymentMethodCmd.MarkFlagRequired("payment-method-id")
}
