// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var paymentsGetPaymentCmd = &cobra.Command{
	Use:   "get-payment",
	Short: "Get a payment",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/account/payments/{paymentId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		paymentIdVal, _ := cmd.Flags().GetString("payment-id")
		if paymentIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "payment-id")
		}
		path = strings.Replace(path, "{paymentId}", paymentIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	paymentsGetPaymentCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = paymentsGetPaymentCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = paymentsGetPaymentCmd.MarkFlagRequired("api-version")
	paymentsGetPaymentCmd.Flags().String("payment-id", "", "The ID of the Payment to look up.")
	_ = paymentsGetPaymentCmd.MarkFlagRequired("payment-id")
}
