// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var personalAccessTokensDeletePersonalAccessTokenCmd = &cobra.Command{
	Use:   "delete-personal-access-token",
	Short: "Revoke a personal access token",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/profile/tokens/{tokenId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tokenIdVal, _ := cmd.Flags().GetString("token-id")
		if tokenIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "token-id")
		}
		path = strings.Replace(path, "{tokenId}", tokenIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	personalAccessTokensDeletePersonalAccessTokenCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = personalAccessTokensDeletePersonalAccessTokenCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = personalAccessTokensDeletePersonalAccessTokenCmd.MarkFlagRequired("api-version")
	personalAccessTokensDeletePersonalAccessTokenCmd.Flags().String("token-id", "", "The ID of the token to access.")
	_ = personalAccessTokensDeletePersonalAccessTokenCmd.MarkFlagRequired("token-id")
}
