// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var personalAccessTokensPutPersonalAccessTokenCmd = &cobra.Command{
	Use:   "put-personal-access-token",
	Short: "Update a personal access token",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/profile/tokens/{tokenId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tokenIdVal, _ := cmd.Flags().GetString("token-id")
		if tokenIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "token-id")
		}
		path = strings.Replace(path, "{tokenId}", tokenIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "created", JSONPath: "created", Type: "string"},
			{FlagName: "expiry", JSONPath: "expiry", Type: "string"},
			{FlagName: "id", JSONPath: "id", Type: "integer"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "scopes", JSONPath: "scopes", Type: "string"},
			{FlagName: "token", JSONPath: "token", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = personalAccessTokensPutPersonalAccessTokenCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = personalAccessTokensPutPersonalAccessTokenCmd.MarkFlagRequired("api-version")
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("token-id", "", "The ID of the token to access.")
	_ = personalAccessTokensPutPersonalAccessTokenCmd.MarkFlagRequired("token-id")
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("created", "", "__Filterable__, __Read-only__ The date and time this token was created.")
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("expiry", "", "__Read-only__ When this token will expire. Personal Access Tokens cannot be renewed, so after this time the token will be completely unusable and a new token will need to be generated. Tokens may be created with `null` as their expiry and will never expire unless revoked.")
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("id", "", "__Read-only__ This token's unique ID, which can be used to revoke it.")
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("label", "", "__Filterable__ This token's label. This is for display purposes only, but can be used to more easily track what you're using each token for.")
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("scopes", "", "__Read-only__ The scopes this token was created with. These define what parts of the Account the token can be used to access. Many command-line tools, such as the [Linode CLI](https://github.com/linode/linode-cli), require tokens with access to `*`. Tokens with more restrictive scopes are generally more secure.")
	personalAccessTokensPutPersonalAccessTokenCmd.Flags().String("token", "", "__Read-only__ The token used to access the API. When the token is created, the full token is returned here. Otherwise, only the first 16 characters are returned.")
}
