// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var phoneNumberPostProfilePhoneNumberVerifyCmd = &cobra.Command{
	Use:   "post-profile-phone-number-verify",
	Short: "Verify a phone number",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/profile/phone-number/verify"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "otp-code", JSONPath: "otp_code", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	phoneNumberPostProfilePhoneNumberVerifyCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = phoneNumberPostProfilePhoneNumberVerifyCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = phoneNumberPostProfilePhoneNumberVerifyCmd.MarkFlagRequired("api-version")
	phoneNumberPostProfilePhoneNumberVerifyCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	phoneNumberPostProfilePhoneNumberVerifyCmd.Flags().String("otp-code", "", "The one-time code received via SMS message after running the [Send a phone number verification code](https://techdocs.akamai.com/linode-api/reference/post-profile-phone-number) operation.")
	_ = phoneNumberPostProfilePhoneNumberVerifyCmd.MarkFlagRequired("otp-code")
}
