// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var placementGroupsPutPlacementGroupCmd = &cobra.Command{
	Use:   "put-placement-group",
	Short: "Update a placement group",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/placement/groups/{groupId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		groupIdVal, _ := cmd.Flags().GetString("group-id")
		if groupIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "group-id")
		}
		path = strings.Replace(path, "{groupId}", groupIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "label", JSONPath: "label", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	placementGroupsPutPlacementGroupCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = placementGroupsPutPlacementGroupCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = placementGroupsPutPlacementGroupCmd.MarkFlagRequired("api-version")
	placementGroupsPutPlacementGroupCmd.Flags().String("group-id", "", "ID of the placement group to look up. Run the [List placement groups](https://techdocs.akamai.com/linode-api/reference/get-placement-groups) operation and store the `id` for the applicable placement group.")
	_ = placementGroupsPutPlacementGroupCmd.MarkFlagRequired("group-id")
	placementGroupsPutPlacementGroupCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	placementGroupsPutPlacementGroupCmd.Flags().String("label", "", "A unique name for the placement group. A placement group `label` has the following constraints: - It needs to begin and end with an alphanumeric character. - It can only consist of alphanumeric characters, hyphens (`-`), underscores (`_`), or periods (`.`).")
}
