// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var postgresqlPostDatabasesPostgreSqlConnPoolsCmd = &cobra.Command{
	Use:   "post-databases-postgre-sql-conn-pools",
	Short: "Create a PostgreSQL connection pool",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/databases/postgresql/instances/{postgresqlInstanceId}/connection-pools"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		postgresqlInstanceIdVal, _ := cmd.Flags().GetString("postgresql-instance-id")
		if postgresqlInstanceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "postgresql-instance-id")
		}
		path = strings.Replace(path, "{postgresqlInstanceId}", postgresqlInstanceIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "database", JSONPath: "database", Type: "string"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "mode", JSONPath: "mode", Type: "string"},
			{FlagName: "size", JSONPath: "size", Type: "integer"},
			{FlagName: "username", JSONPath: "username", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	postgresqlPostDatabasesPostgreSqlConnPoolsCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = postgresqlPostDatabasesPostgreSqlConnPoolsCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = postgresqlPostDatabasesPostgreSqlConnPoolsCmd.MarkFlagRequired("api-version")
	postgresqlPostDatabasesPostgreSqlConnPoolsCmd.Flags().String("postgresql-instance-id", "", "The unique identifier for a PostgreSQL Managed Database. Run the [List PostgreSQL Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-postgre-sql-instances) operation and store the `id` for the desired one.")
	_ = postgresqlPostDatabasesPostgreSqlConnPoolsCmd.MarkFlagRequired("postgresql-instance-id")
	postgresqlPostDatabasesPostgreSqlConnPoolsCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	postgresqlPostDatabasesPostgreSqlConnPoolsCmd.Flags().String("database", "defaultdb", "The name of the PostgreSQL Managed Database where the connection pool is assigned. Run the [List PostgreSQL Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-postgre-sql-instances) operation and store the `label` for the target database.")
	postgresqlPostDatabasesPostgreSqlConnPoolsCmd.Flags().String("label", "", "The name of the connection pool. These points apply: - A `label` needs to be unique in a database instance. - A `label` can contain alphanumeric characters, underscores, or hyphens, and it can't start with hyphen. - A `label` has a maximum length of 63 characters.")
	_ = postgresqlPostDatabasesPostgreSqlConnPoolsCmd.MarkFlagRequired("label")
	postgresqlPostDatabasesPostgreSqlConnPoolsCmd.Flags().String("mode", "transaction", "Set the connection pooling mode based on the specification set by our partner, [Aiven](https://aiven.io/docs/products/postgresql/concepts/pg-connection-pooling#pooling-modes). Select from `transaction`, `session`, or `statement`.")
	_ = postgresqlPostDatabasesPostgreSqlConnPoolsCmd.RegisterFlagCompletionFunc("mode", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"session", "statement", "transaction"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = postgresqlPostDatabasesPostgreSqlConnPoolsCmd.MarkFlagRequired("mode")
	postgresqlPostDatabasesPostgreSqlConnPoolsCmd.Flags().String("size", "10", "The number of connections in the pool. This can't exceed the number of available connections for your service plan.")
	_ = postgresqlPostDatabasesPostgreSqlConnPoolsCmd.MarkFlagRequired("size")
	postgresqlPostDatabasesPostgreSqlConnPoolsCmd.Flags().String("username", "null", "The username of the client making the connection. The default of `null` reuses the inbound user.")
	_ = postgresqlPostDatabasesPostgreSqlConnPoolsCmd.MarkFlagRequired("username")
}
