// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var reviewBetaProgramsCmd = &cobra.Command{
	Use:   "review-beta-programs",
	Short: "review-beta-programs operations",
}
