// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var reviewBetaProgramsGetBetaProgramCmd = &cobra.Command{
	Use:   "get-beta-program",
	Short: "Get a Beta program",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/betas/{betaId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		betaIdVal, _ := cmd.Flags().GetString("beta-id")
		if betaIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "beta-id")
		}
		path = strings.Replace(path, "{betaId}", betaIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	reviewBetaProgramsGetBetaProgramCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = reviewBetaProgramsGetBetaProgramCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = reviewBetaProgramsGetBetaProgramCmd.MarkFlagRequired("api-version")
	reviewBetaProgramsGetBetaProgramCmd.Flags().String("beta-id", "", "The unique identifier for the Beta program.")
	_ = reviewBetaProgramsGetBetaProgramCmd.MarkFlagRequired("beta-id")
}
