// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var stackscriptsDeleteStackScriptCmd = &cobra.Command{
	Use:   "delete-stack-script",
	Short: "Delete a StackScript",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/stackscripts/{stackscriptId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		stackscriptIdVal, _ := cmd.Flags().GetString("stackscript-id")
		if stackscriptIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "stackscript-id")
		}
		path = strings.Replace(path, "{stackscriptId}", stackscriptIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	stackscriptsDeleteStackScriptCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = stackscriptsDeleteStackScriptCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = stackscriptsDeleteStackScriptCmd.MarkFlagRequired("api-version")
	stackscriptsDeleteStackScriptCmd.Flags().String("stackscript-id", "", "The ID of the StackScript to look up.")
	_ = stackscriptsDeleteStackScriptCmd.MarkFlagRequired("stackscript-id")
}
