// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var stackscriptsPutStackScriptCmd = &cobra.Command{
	Use:   "put-stack-script",
	Short: "Update a StackScript",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/linode/stackscripts/{stackscriptId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		stackscriptIdVal, _ := cmd.Flags().GetString("stackscript-id")
		if stackscriptIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "stackscript-id")
		}
		path = strings.Replace(path, "{stackscriptId}", stackscriptIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "created", JSONPath: "created", Type: "string"},
			{FlagName: "deployments-active", JSONPath: "deployments_active", Type: "integer"},
			{FlagName: "deployments-total", JSONPath: "deployments_total", Type: "integer"},
			{FlagName: "description", JSONPath: "description", Type: "string"},
			{FlagName: "id", JSONPath: "id", Type: "integer"},
			{FlagName: "images", JSONPath: "images", Type: "array"},
			{FlagName: "is-public", JSONPath: "is_public", Type: "boolean"},
			{FlagName: "label", JSONPath: "label", Type: "string"},
			{FlagName: "mine", JSONPath: "mine", Type: "boolean"},
			{FlagName: "rev-note", JSONPath: "rev_note", Type: "string"},
			{FlagName: "script", JSONPath: "script", Type: "string"},
			{FlagName: "updated", JSONPath: "updated", Type: "string"},
			{FlagName: "user-defined-fields", JSONPath: "user_defined_fields", Type: "array"},
			{FlagName: "user-gravatar-id", JSONPath: "user_gravatar_id", Type: "string"},
			{FlagName: "username", JSONPath: "username", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	stackscriptsPutStackScriptCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = stackscriptsPutStackScriptCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = stackscriptsPutStackScriptCmd.MarkFlagRequired("api-version")
	stackscriptsPutStackScriptCmd.Flags().String("stackscript-id", "", "The ID of the StackScript to look up.")
	_ = stackscriptsPutStackScriptCmd.MarkFlagRequired("stackscript-id")
	stackscriptsPutStackScriptCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	stackscriptsPutStackScriptCmd.Flags().String("created", "", "__Read-only__ The date this StackScript was created.")
	stackscriptsPutStackScriptCmd.Flags().String("deployments-active", "", "__Read-only__ Count of currently active, deployed Linodes created from this StackScript.")
	stackscriptsPutStackScriptCmd.Flags().String("deployments-total", "", "__Filterable__, __Read-only__ The total number of times this StackScript has been deployed.")
	stackscriptsPutStackScriptCmd.Flags().String("description", "", "__Filterable__ A description for the StackScript.")
	stackscriptsPutStackScriptCmd.Flags().String("id", "", "__Read-only__ The unique ID of this StackScript.")
	stackscriptsPutStackScriptCmd.Flags().String("images", "", "An array of Image IDs. These are the Images that can be deployed with this StackScript. `any/all` indicates that all available Images, including private Images, are accepted.")
	stackscriptsPutStackScriptCmd.Flags().String("is-public", "", "__Filterable__ This determines whether other users can use your StackScript. __Once a StackScript is made public, it cannot be made private.__")
	stackscriptsPutStackScriptCmd.Flags().String("label", "", "__Filterable__ The StackScript's label is for display purposes only.")
	stackscriptsPutStackScriptCmd.Flags().String("mine", "", "__Filterable__, __Read-only__ Returns `true` if this StackScript is owned by the account of the user making the request, and the user making the request is unrestricted or has access to this StackScript.")
	stackscriptsPutStackScriptCmd.Flags().String("rev-note", "", "__Filterable__ This field allows you to add notes for the set of revisions made to this StackScript.")
	stackscriptsPutStackScriptCmd.Flags().String("script", "", "The script to execute when provisioning a new Linode with this StackScript.")
	stackscriptsPutStackScriptCmd.Flags().String("updated", "", "__Read-only__ The date this StackScript was last updated.")
	stackscriptsPutStackScriptCmd.Flags().String("user-defined-fields", "", "__Read-only__ This is a list of fields defined with a special syntax inside this StackScript that allow for supplying customized parameters during deployment. See [Declare User-Defined Fields (UDFs)](https://techdocs.akamai.com/cloud-computing/docs/write-a-custom-script-for-use-with-stackscripts#declare-user-defined-fields-udfs) for more information.")
	stackscriptsPutStackScriptCmd.Flags().String("user-gravatar-id", "", "__Read-only__ The Gravatar ID for the User who created the StackScript.")
	stackscriptsPutStackScriptCmd.Flags().String("username", "", "__Read-only__ The User who created the StackScript.")
}
