// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var tagsDeleteTagCmd = &cobra.Command{
	Use:   "delete-tag",
	Short: "Delete a tag",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/tags/{tagLabel}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		tagLabelVal, _ := cmd.Flags().GetString("tag-label")
		if tagLabelVal == "" {
			return fmt.Errorf("required flag --%s not set", "tag-label")
		}
		path = strings.Replace(path, "{tagLabel}", tagLabelVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	tagsDeleteTagCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = tagsDeleteTagCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = tagsDeleteTagCmd.MarkFlagRequired("api-version")
	tagsDeleteTagCmd.Flags().String("tag-label", "", "The `label` of the tag to access.")
	_ = tagsDeleteTagCmd.MarkFlagRequired("tag-label")
}
