// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var tlsSslCertificatesPostObjectStorageSslCmd = &cobra.Command{
	Use:   "post-object-storage-ssl",
	Short: "Upload an Object Storage TLS/SSL certificate",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/object-storage/buckets/{regionId}/{bucket}/ssl"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		regionIdVal, _ := cmd.Flags().GetString("region-id")
		if regionIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "region-id")
		}
		path = strings.Replace(path, "{regionId}", regionIdVal, 1)
		bucketVal, _ := cmd.Flags().GetString("bucket")
		if bucketVal == "" {
			return fmt.Errorf("required flag --%s not set", "bucket")
		}
		path = strings.Replace(path, "{bucket}", bucketVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "certificate", JSONPath: "certificate", Type: "string"},
			{FlagName: "private-key", JSONPath: "private_key", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	tlsSslCertificatesPostObjectStorageSslCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = tlsSslCertificatesPostObjectStorageSslCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = tlsSslCertificatesPostObjectStorageSslCmd.MarkFlagRequired("api-version")
	tlsSslCertificatesPostObjectStorageSslCmd.Flags().String("region-id", "", "Identifies a region where this bucket lives. > blue-book > > You can use a `clusterId` in place of `regionId` in requests for buckets that you created using the legacy version of the API. Run [List clusters](https://techdocs.akamai.com/linode-api/reference/get-object-storage-clusters) to see each cluster `id`.")
	_ = tlsSslCertificatesPostObjectStorageSslCmd.MarkFlagRequired("region-id")
	tlsSslCertificatesPostObjectStorageSslCmd.Flags().String("bucket", "", "The bucket name.")
	_ = tlsSslCertificatesPostObjectStorageSslCmd.MarkFlagRequired("bucket")
	tlsSslCertificatesPostObjectStorageSslCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	tlsSslCertificatesPostObjectStorageSslCmd.Flags().String("certificate", "", "Your Base64 encoded and PEM formatted SSL certificate. Line breaks must be represented as `\\n` in the string for requests (but not when using the Linode CLI)")
	_ = tlsSslCertificatesPostObjectStorageSslCmd.MarkFlagRequired("certificate")
	tlsSslCertificatesPostObjectStorageSslCmd.Flags().String("private-key", "", "The private key associated with this TLS/SSL certificate. Line breaks must be represented as `\\n` in the string for requests (but not when using the Linode CLI)")
	_ = tlsSslCertificatesPostObjectStorageSslCmd.MarkFlagRequired("private-key")
}
