// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var trustedDevicesGetTrustedDeviceCmd = &cobra.Command{
	Use:   "get-trusted-device",
	Short: "Get a trusted device",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/profile/devices/{deviceId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		deviceIdVal, _ := cmd.Flags().GetString("device-id")
		if deviceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "device-id")
		}
		path = strings.Replace(path, "{deviceId}", deviceIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	trustedDevicesGetTrustedDeviceCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = trustedDevicesGetTrustedDeviceCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = trustedDevicesGetTrustedDeviceCmd.MarkFlagRequired("api-version")
	trustedDevicesGetTrustedDeviceCmd.Flags().String("device-id", "", "The ID of the TrustedDevice.")
	_ = trustedDevicesGetTrustedDeviceCmd.MarkFlagRequired("device-id")
}
