// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var trustedDevicesCmd = &cobra.Command{
	Use:   "trusted-devices",
	Short: "trusted-devices operations",
}
