// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var twoFactorAuthenticationPostTfaConfirmCmd = &cobra.Command{
	Use:   "post-tfa-confirm",
	Short: "Enable two-factor authentication",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/profile/tfa-enable-confirm"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "tfa-code", JSONPath: "tfa_code", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	twoFactorAuthenticationPostTfaConfirmCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = twoFactorAuthenticationPostTfaConfirmCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = twoFactorAuthenticationPostTfaConfirmCmd.MarkFlagRequired("api-version")
	twoFactorAuthenticationPostTfaConfirmCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	twoFactorAuthenticationPostTfaConfirmCmd.Flags().String("tfa-code", "", "The Two Factor code you generated with your Two Factor secret. These codes are time-based, so be sure it is current.")
}
