// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linodectl/cli/runtime"
	"github.com/spf13/cobra"
)

var volumesPostResizeVolumeCmd = &cobra.Command{
	Use:   "post-resize-volume",
	Short: "Resize a volume",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/volumes/{volumeId}/resize"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		volumeIdVal, _ := cmd.Flags().GetString("volume-id")
		if volumeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "volume-id")
		}
		path = strings.Replace(path, "{volumeId}", volumeIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "size", JSONPath: "size", Type: "integer"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	volumesPostResizeVolumeCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = volumesPostResizeVolumeCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = volumesPostResizeVolumeCmd.MarkFlagRequired("api-version")
	volumesPostResizeVolumeCmd.Flags().String("volume-id", "", "The unique identifier for the target volume. Run the [List volumes](https://techdocs.akamai.com/linode-api/reference/get-volumes) operation and store the `id` for the target volume as your `volumeId`.")
	_ = volumesPostResizeVolumeCmd.MarkFlagRequired("volume-id")
	volumesPostResizeVolumeCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	volumesPostResizeVolumeCmd.Flags().String("size", "", "The volume's size, in gigabytes.")
	_ = volumesPostResizeVolumeCmd.MarkFlagRequired("size")
}
