// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var vpcSubnetsPutVpcSubnetCmd = &cobra.Command{
	Use:   "put-vpc-subnet",
	Short: "Update a VPC subnet",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/vpcs/{vpcId}/subnets/{vpcSubnetId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		vpcIdVal, _ := cmd.Flags().GetString("vpc-id")
		if vpcIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "vpc-id")
		}
		path = strings.Replace(path, "{vpcId}", vpcIdVal, 1)
		vpcSubnetIdVal, _ := cmd.Flags().GetString("vpc-subnet-id")
		if vpcSubnetIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "vpc-subnet-id")
		}
		path = strings.Replace(path, "{vpcSubnetId}", vpcSubnetIdVal, 1)

		params := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "label", JSONPath: "label", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	vpcSubnetsPutVpcSubnetCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = vpcSubnetsPutVpcSubnetCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = vpcSubnetsPutVpcSubnetCmd.MarkFlagRequired("api-version")
	vpcSubnetsPutVpcSubnetCmd.Flags().String("vpc-id", "", "The `id` of the VPC.")
	_ = vpcSubnetsPutVpcSubnetCmd.MarkFlagRequired("vpc-id")
	vpcSubnetsPutVpcSubnetCmd.Flags().String("vpc-subnet-id", "", "The `id` of the VPC Subnet.")
	_ = vpcSubnetsPutVpcSubnetCmd.MarkFlagRequired("vpc-subnet-id")
	vpcSubnetsPutVpcSubnetCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	vpcSubnetsPutVpcSubnetCmd.Flags().String("label", "", "__Filterable__ The VPC Subnet's label, for display purposes only. - Must be unique among the VPC's Subnets. - Can only contain ASCII letters, numbers, and hyphens (`-`). You can't use two consecutive hyphens (`--`).")
}
