// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/jghiloni/linode-cli/cli/runtime"
	"github.com/spf13/cobra"
)

var vpcSubnetsGetVpcSubnetCmd = &cobra.Command{
	Use:   "get-vpc-subnet",
	Short: "Get a VPC subnet",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/{apiVersion}/vpcs/{vpcId}/subnets/{vpcSubnetId}"
		apiVersionVal, _ := cmd.Flags().GetString("api-version")
		if apiVersionVal == "" {
			return fmt.Errorf("required flag --%s not set", "api-version")
		}
		path = strings.Replace(path, "{apiVersion}", apiVersionVal, 1)
		vpcIdVal, _ := cmd.Flags().GetString("vpc-id")
		if vpcIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "vpc-id")
		}
		path = strings.Replace(path, "{vpcId}", vpcIdVal, 1)
		vpcSubnetIdVal, _ := cmd.Flags().GetString("vpc-subnet-id")
		if vpcSubnetIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "vpc-subnet-id")
		}
		path = strings.Replace(path, "{vpcSubnetId}", vpcSubnetIdVal, 1)

		params := make(map[string]string)
		resp, err := client.Do("GET", path, params, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	vpcSubnetsGetVpcSubnetCmd.Flags().String("api-version", "", "__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
	_ = vpcSubnetsGetVpcSubnetCmd.RegisterFlagCompletionFunc("api-version", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"v4", "v4beta"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = vpcSubnetsGetVpcSubnetCmd.MarkFlagRequired("api-version")
	vpcSubnetsGetVpcSubnetCmd.Flags().String("vpc-id", "", "The `id` of the VPC.")
	_ = vpcSubnetsGetVpcSubnetCmd.MarkFlagRequired("vpc-id")
	vpcSubnetsGetVpcSubnetCmd.Flags().String("vpc-subnet-id", "", "The `id` of the VPC Subnet.")
	_ = vpcSubnetsGetVpcSubnetCmd.MarkFlagRequired("vpc-subnet-id")
}
