// Code generated by onlycli; DO NOT EDIT.

package commands

import "github.com/spf13/cobra"

var vpcIpAddressesCmd = &cobra.Command{
	Use:   "vpc-ip-addresses",
	Short: "vpc-ip-addresses operations",
}
