// Code generated by onlycli; DO NOT EDIT.

package runtime

import (
	"bufio"
	"bytes"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/tabwriter"
	"text/template"

	"github.com/spf13/cobra"
	"github.com/tidwall/gjson"
	"gopkg.in/yaml.v3"
)

// formatOutputCell renders a JSON-decoded value as a single table/CSV cell.
func formatOutputCell(v interface{}) string {
	if v == nil {
		return ""
	}
	switch x := v.(type) {
	case string:
		return x
	case bool, float64, int, int32, int64, uint, uint32, uint64:
		return fmt.Sprint(x)
	default:
		b, err := json.Marshal(x)
		if err != nil {
			return fmt.Sprint(x)
		}
		return string(b)
	}
}

// PrintOutput formats resp.Body according to --format, --transform, --template, and status.
func PrintOutput(cmd *cobra.Command, resp *Response) error {
	if resp == nil {
		return nil
	}

	if resp.StreamReader != nil {
		return printStreamOutput(cmd, resp)
	}

	success := resp.StatusCode == 0 || (resp.StatusCode >= 200 && resp.StatusCode < 300)
	out := cmd.OutOrStdout()
	if !success {
		out = cmd.ErrOrStderr()
		fmt.Fprintf(out, "HTTP %d\n", resp.StatusCode)
	}

	if len(resp.Body) == 0 {
		return nil
	}

	format, _ := cmd.Flags().GetString("format")
	format = strings.TrimSpace(format)
	if format == "" {
		format = "json"
	}
	transform, _ := cmd.Flags().GetString("transform")
	transform = strings.TrimSpace(transform)
	templateStr, templateErr := cmd.Flags().GetString("template")
	if templateErr != nil {
		templateStr = ""
	}
	templateStr = strings.TrimSpace(templateStr)

	data := resp.Body
	if format != "raw" && transform != "" {
		res := gjson.GetBytes(data, transform)
		data = []byte(res.Raw)
	}

	if templateStr != "" {
		tmpl, err := template.New("out").Funcs(template.FuncMap{
			"join":  strings.Join,
			"upper": strings.ToUpper,
			"lower": strings.ToLower,
		}).Parse(templateStr)
		if err != nil {
			return fmt.Errorf("parse template: %w", err)
		}
		var v interface{}
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("template: unmarshal json: %w", err)
		}
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, v); err != nil {
			return fmt.Errorf("template: execute: %w", err)
		}
		_, werr := out.Write(buf.Bytes())
		return werr
	}

	switch format {
	case "raw":
		_, err := out.Write(data)
		return err
	case "json":
		var buf bytes.Buffer
		if err := json.Compact(&buf, data); err != nil {
			return fmt.Errorf("compact json: %w", err)
		}
		_, err := fmt.Fprintln(out, buf.String())
		return err
	case "pretty":
		var buf bytes.Buffer
		if err := json.Indent(&buf, data, "", "  "); err != nil {
			return fmt.Errorf("indent json: %w", err)
		}
		_, err := fmt.Fprintln(out, buf.String())
		return err
	case "yaml":
		var v interface{}
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("json to yaml: %w", err)
		}
		y, err := yaml.Marshal(v)
		if err != nil {
			return fmt.Errorf("marshal yaml: %w", err)
		}
		_, err = fmt.Fprint(out, string(y))
		return err
	case "jsonl":
		var elems []json.RawMessage
		if err := json.Unmarshal(data, &elems); err != nil {
			return fmt.Errorf("jsonl expects a JSON array: %w", err)
		}
		for _, elem := range elems {
			line, err := json.Marshal(elem)
			if err != nil {
				return fmt.Errorf("jsonl marshal element: %w", err)
			}
			if _, err := fmt.Fprintln(out, string(line)); err != nil {
				return err
			}
		}
		return nil
	case "table":
		var rows []map[string]interface{}
		if err := json.Unmarshal(data, &rows); err != nil || len(rows) == 0 {
			var buf bytes.Buffer
			if err := json.Compact(&buf, data); err != nil {
				return fmt.Errorf("compact json: %w", err)
			}
			_, err := fmt.Fprintln(out, buf.String())
			return err
		}
		first := rows[0]
		headers := make([]string, 0, len(first))
		for k := range first {
			headers = append(headers, k)
		}
		sort.Strings(headers)
		tw := tabwriter.NewWriter(out, 0, 0, 2, ' ', 0)
		for i, h := range headers {
			if i > 0 {
				fmt.Fprint(tw, "\t")
			}
			fmt.Fprint(tw, strings.ToUpper(h))
		}
		fmt.Fprintln(tw, "")
		for _, row := range rows {
			for i, h := range headers {
				if i > 0 {
					fmt.Fprint(tw, "\t")
				}
				fmt.Fprint(tw, formatOutputCell(row[h]))
			}
			fmt.Fprintln(tw, "")
		}
		return tw.Flush()
	case "csv":
		var rows []map[string]interface{}
		if err := json.Unmarshal(data, &rows); err != nil || len(rows) == 0 {
			var buf bytes.Buffer
			if err := json.Compact(&buf, data); err != nil {
				return fmt.Errorf("compact json: %w", err)
			}
			_, err := fmt.Fprintln(out, buf.String())
			return err
		}
		first := rows[0]
		headers := make([]string, 0, len(first))
		for k := range first {
			headers = append(headers, k)
		}
		sort.Strings(headers)
		w := csv.NewWriter(out)
		headerRecord := make([]string, len(headers))
		for i, h := range headers {
			headerRecord[i] = h
		}
		if err := w.Write(headerRecord); err != nil {
			return fmt.Errorf("csv header: %w", err)
		}
		for _, row := range rows {
			rec := make([]string, len(headers))
			for i, h := range headers {
				rec[i] = formatOutputCell(row[h])
			}
			if err := w.Write(rec); err != nil {
				return fmt.Errorf("csv row: %w", err)
			}
		}
		w.Flush()
		return w.Error()
	default:
		fmt.Fprintf(os.Stderr, "unknown --format %q, using json\n", format)
		var buf bytes.Buffer
		if err := json.Compact(&buf, data); err != nil {
			return fmt.Errorf("compact json: %w", err)
		}
		_, err := fmt.Fprintln(out, buf.String())
		return err
	}
}

// printStreamOutput reads a streaming response line-by-line and prints each
// chunk to stdout. Handles SSE (text/event-stream) and NDJSON formats.
func printStreamOutput(cmd *cobra.Command, resp *Response) error {
	defer resp.StreamReader.Close()

	out := cmd.OutOrStdout()

	format, _ := cmd.Flags().GetString("format")
	format = strings.TrimSpace(format)
	if format == "" {
		format = "json"
	}

	contentType := resp.Headers.Get("Content-Type")
	isSSE := strings.Contains(contentType, "text/event-stream")

	scanner := bufio.NewScanner(resp.StreamReader)
	buf := make([]byte, 0, 64*1024)
	scanner.Buffer(buf, 1024*1024)

	for scanner.Scan() {
		line := scanner.Bytes()

		if isSSE {
			if bytes.HasPrefix(line, []byte("data: ")) {
				line = bytes.TrimPrefix(line, []byte("data: "))
				if string(line) == "[DONE]" {
					break
				}
			} else {
				continue
			}
		}

		trimmed := bytes.TrimSpace(line)
		if len(trimmed) == 0 {
			continue
		}

		switch format {
		case "raw":
			fmt.Fprintln(out, string(trimmed))
		case "pretty":
			var pretty bytes.Buffer
			if json.Indent(&pretty, trimmed, "", "  ") == nil {
				fmt.Fprintln(out, pretty.String())
			} else {
				fmt.Fprintln(out, string(trimmed))
			}
		default:
			var compact bytes.Buffer
			if json.Compact(&compact, trimmed) == nil {
				fmt.Fprintln(out, compact.String())
			} else {
				fmt.Fprintln(out, string(trimmed))
			}
		}
	}

	return scanner.Err()
}
